/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    InlineObject,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    InlineObject10,
    InlineObject10FromJSON,
    InlineObject10ToJSON,
    InlineObject11,
    InlineObject11FromJSON,
    InlineObject11ToJSON,
    InlineObject2,
    InlineObject2FromJSON,
    InlineObject2ToJSON,
    InlineObject3,
    InlineObject3FromJSON,
    InlineObject3ToJSON,
    InlineObject4,
    InlineObject4FromJSON,
    InlineObject4ToJSON,
    InlineObject5,
    InlineObject5FromJSON,
    InlineObject5ToJSON,
    InlineObject6,
    InlineObject6FromJSON,
    InlineObject6ToJSON,
    InlineObject7,
    InlineObject7FromJSON,
    InlineObject7ToJSON,
    InlineObject8,
    InlineObject8FromJSON,
    InlineObject8ToJSON,
    InlineObject9,
    InlineObject9FromJSON,
    InlineObject9ToJSON,
    InlineResponse200,
    InlineResponse200FromJSON,
    InlineResponse200ToJSON,
    InlineResponse2001,
    InlineResponse2001FromJSON,
    InlineResponse2001ToJSON,
    InlineResponse20010,
    InlineResponse20010FromJSON,
    InlineResponse20010ToJSON,
    InlineResponse20011,
    InlineResponse20011FromJSON,
    InlineResponse20011ToJSON,
    InlineResponse20012,
    InlineResponse20012FromJSON,
    InlineResponse20012ToJSON,
    InlineResponse20013,
    InlineResponse20013FromJSON,
    InlineResponse20013ToJSON,
    InlineResponse20014,
    InlineResponse20014FromJSON,
    InlineResponse20014ToJSON,
    InlineResponse2002,
    InlineResponse2002FromJSON,
    InlineResponse2002ToJSON,
    InlineResponse2002BookAuthors,
    InlineResponse2002BookAuthorsFromJSON,
    InlineResponse2002BookAuthorsToJSON,
    InlineResponse2003,
    InlineResponse2003FromJSON,
    InlineResponse2003ToJSON,
    InlineResponse2004,
    InlineResponse2004FromJSON,
    InlineResponse2004ToJSON,
    InlineResponse2004ResourceTracks,
    InlineResponse2004ResourceTracksFromJSON,
    InlineResponse2004ResourceTracksToJSON,
    InlineResponse2004Topics,
    InlineResponse2004TopicsFromJSON,
    InlineResponse2004TopicsToJSON,
    InlineResponse2005,
    InlineResponse2005FromJSON,
    InlineResponse2005ToJSON,
    InlineResponse2005Books,
    InlineResponse2005BooksFromJSON,
    InlineResponse2005BooksToJSON,
    InlineResponse2006,
    InlineResponse2006FromJSON,
    InlineResponse2006ToJSON,
    InlineResponse2007,
    InlineResponse2007FromJSON,
    InlineResponse2007ToJSON,
    InlineResponse2008,
    InlineResponse2008FromJSON,
    InlineResponse2008ToJSON,
    InlineResponse2009,
    InlineResponse2009FromJSON,
    InlineResponse2009ToJSON,
    InlineResponse201,
    InlineResponse201FromJSON,
    InlineResponse201ToJSON,
    InlineResponse2011,
    InlineResponse2011FromJSON,
    InlineResponse2011ToJSON,
} from '../models';

export interface ApiV2ActivityGetRequest {
    currentLtiContextOnly?: boolean;
}

export interface ApiV2BookBookIdActivityGetRequest {
    bookId: number;
    currentLtiContextOnly?: boolean;
}

export interface ApiV2BookBookIdActivityPutRequest {
    bookId: number;
    currentLtiContextOnly?: boolean;
}

export interface ApiV2BookBookIdAuthorsPutRequest {
    bookId: number;
    body?: InlineObject4;
}

export interface ApiV2BookBookIdDeleteRequest {
    bookId: number;
}

export interface ApiV2BookBookIdGetRequest {
    bookId: number;
}

export interface ApiV2BookBookIdPutRequest {
    bookId: number;
    body?: InlineObject2;
}

export interface ApiV2BookPostRequest {
    body?: InlineObject3;
}

export interface ApiV2BookPublicTokenGetRequest {
    token: string;
    originreferer?: string;
}

export interface ApiV2BookZoomMeetingIdGetRequest {
    meetingId: number;
}

export interface ApiV2BooksGetRequest {
    sort?: string;
    page?: number;
    perPage?: number;
}

export interface ApiV2BooksImportPostRequest {
    body?: InlineObject5;
}

export interface ApiV2EventPostRequest {
    body?: InlineObject11;
}

export interface ApiV2LtiCallbackPostRequest {
    state: string;
    idToken: string;
}

export interface ApiV2LtiLaunchPostRequest {
    oauthVersion: string;
    oauthNonce: string;
    oauthTimestamp: string;
    oauthConsumerKey: string;
    oauthSignatureMethod: string;
    oauthSignature: string;
    ltiMessageType: string;
    ltiVersion: string;
    resourceLinkId: string;
    userId: string;
    roles: string;
    contextId: string;
    resourceLinkTitle?: string;
    contextTitle?: string;
    contextLabel?: string;
    lisPersonNameFull?: string;
    lisPersonContactEmailPrimary?: string;
    launchPresentationReturnUrl?: string;
}

export interface ApiV2LtiLoginGetRequest {
    iss: string;
    loginHint: string;
    targetLinkUri: string;
    clientId: string;
    ltiMessageHint?: string;
    ltiDeploymentId?: string;
}

export interface ApiV2LtiLoginPostRequest {
    iss: string;
    loginHint: string;
    targetLinkUri: string;
    clientId: string;
    ltiMessageHint?: string;
    ltiDeploymentId?: string;
}

export interface ApiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdDeleteRequest {
    ltiConsumerId: string;
    ltiResourceLinkId: string;
}

export interface ApiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdGetRequest {
    ltiConsumerId: string;
    ltiResourceLinkId: string;
}

export interface ApiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdPutRequest {
    ltiConsumerId: string;
    ltiResourceLinkId: string;
    body?: InlineObject;
}

export interface ApiV2LtiSearchGetRequest {
    q: string;
    sort?: ApiV2LtiSearchGetSortEnum;
    page?: number;
    perPage?: number;
}

export interface ApiV2ResourceResourceIdOembedGetRequest {
    resourceId: number;
}

export interface ApiV2ResourceResourceIdVideoTrackPostRequest {
    resourceId: number;
    body?: InlineObject10;
}

export interface ApiV2ResourceResourceIdVideoTrackVideoTrackIdDeleteRequest {
    videoTrackId: number;
    resourceId: number;
}

export interface ApiV2ResourceResourceIdVideoTrackVideoTrackIdVttGetRequest {
    accessToken: string;
    videoTrackId: number;
    resourceId: number;
}

export interface ApiV2ResourcesGetRequest {
    sort?: string;
    page?: number;
    perPage?: number;
}

export interface ApiV2SearchGetRequest {
    type: ApiV2SearchGetTypeEnum;
    q: string;
    filter?: ApiV2SearchGetFilterEnum;
    sort?: ApiV2SearchGetSortEnum;
    page?: number;
    perPage?: number;
}

export interface ApiV2TopicPostRequest {
    body?: InlineObject7;
}

export interface ApiV2TopicTopicIdActivityPutRequest {
    topicId: number;
    currentLtiContextOnly?: boolean;
    body?: InlineObject8;
}

export interface ApiV2TopicTopicIdAuthorsPutRequest {
    topicId: number;
    body?: InlineObject9;
}

export interface ApiV2TopicTopicIdDeleteRequest {
    topicId: number;
}

export interface ApiV2TopicTopicIdGetRequest {
    topicId: number;
}

export interface ApiV2TopicTopicIdPutRequest {
    topicId: number;
    body?: InlineObject6;
}

export interface ApiV2TopicsGetRequest {
    sort?: string;
    page?: number;
    perPage?: number;
}

export interface ApiV2UserSettingsPutRequest {
    body?: InlineObject1;
}

export interface ApiV2UserUserIdBooksGetRequest {
    userId: number;
    sort?: string;
    page?: number;
    perPage?: number;
}

export interface ApiV2UserUserIdTopicsGetRequest {
    userId: number;
    sort?: string;
    page?: number;
    perPage?: number;
}

export interface ApiV2UsersEmailGetRequest {
    email: string;
}

export interface ApiV2WowzaWildcardGetRequest {
    accessToken: string;
    wildcard: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * 受講者の学習活動の一覧を取得します。 受講者以外の学習活動は含みません。 現在のセッションの LTI Context に紐づくブックに含まれる表示可能なトピックの学習活動を得ます。 教員または管理者でなければなりません。 自身以外の作成した共有されていないブック・トピックの学習活動は含みません。
     * 受講者の学習活動一覧
     */
    async apiV2ActivityGetRaw(requestParameters: ApiV2ActivityGetRequest): Promise<runtime.ApiResponse<InlineResponse20014>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.currentLtiContextOnly !== undefined) {
            queryParameters['current_lti_context_only'] = requestParameters.currentLtiContextOnly;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/activity`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse20014FromJSON(jsonValue));
    }

    /**
     * 受講者の学習活動の一覧を取得します。 受講者以外の学習活動は含みません。 現在のセッションの LTI Context に紐づくブックに含まれる表示可能なトピックの学習活動を得ます。 教員または管理者でなければなりません。 自身以外の作成した共有されていないブック・トピックの学習活動は含みません。
     * 受講者の学習活動一覧
     */
    async apiV2ActivityGet(requestParameters: ApiV2ActivityGetRequest): Promise<InlineResponse20014> {
        const response = await this.apiV2ActivityGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * 現在のセッションの学習状況の詳細を取得します。 自身以外の学習者の学習状況を取得することはできません。
     * 学習状況の取得
     */
    async apiV2BookBookIdActivityGetRaw(requestParameters: ApiV2BookBookIdActivityGetRequest): Promise<runtime.ApiResponse<InlineResponse2008>> {
        if (requestParameters.bookId === null || requestParameters.bookId === undefined) {
            throw new runtime.RequiredError('bookId','Required parameter requestParameters.bookId was null or undefined when calling apiV2BookBookIdActivityGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.currentLtiContextOnly !== undefined) {
            queryParameters['current_lti_context_only'] = requestParameters.currentLtiContextOnly;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/book/{book_id}/activity`.replace(`{${"book_id"}}`, encodeURIComponent(String(requestParameters.bookId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2008FromJSON(jsonValue));
    }

    /**
     * 現在のセッションの学習状況の詳細を取得します。 自身以外の学習者の学習状況を取得することはできません。
     * 学習状況の取得
     */
    async apiV2BookBookIdActivityGet(requestParameters: ApiV2BookBookIdActivityGetRequest): Promise<InlineResponse2008> {
        const response = await this.apiV2BookBookIdActivityGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * 現在のセッションの学習状況の詳細を更新します。 自身以外の学習者の学習状況を更新することはできません。 LTI v1.3 でなければなりません。
     * 学習状況の更新
     */
    async apiV2BookBookIdActivityPutRaw(requestParameters: ApiV2BookBookIdActivityPutRequest): Promise<runtime.ApiResponse<InlineResponse2008>> {
        if (requestParameters.bookId === null || requestParameters.bookId === undefined) {
            throw new runtime.RequiredError('bookId','Required parameter requestParameters.bookId was null or undefined when calling apiV2BookBookIdActivityPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.currentLtiContextOnly !== undefined) {
            queryParameters['current_lti_context_only'] = requestParameters.currentLtiContextOnly;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/book/{book_id}/activity`.replace(`{${"book_id"}}`, encodeURIComponent(String(requestParameters.bookId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2008FromJSON(jsonValue));
    }

    /**
     * 現在のセッションの学習状況の詳細を更新します。 自身以外の学習者の学習状況を更新することはできません。 LTI v1.3 でなければなりません。
     * 学習状況の更新
     */
    async apiV2BookBookIdActivityPut(requestParameters: ApiV2BookBookIdActivityPutRequest): Promise<InlineResponse2008> {
        const response = await this.apiV2BookBookIdActivityPutRaw(requestParameters);
        return await response.value();
    }

    /**
     * ブックの著者を更新します。 教員または管理者でなければなりません。 教員は自身の著作のブックでなければなりません。
     * ブックの著者の更新
     */
    async apiV2BookBookIdAuthorsPutRaw(requestParameters: ApiV2BookBookIdAuthorsPutRequest): Promise<runtime.ApiResponse<Array<InlineResponse2002BookAuthors>>> {
        if (requestParameters.bookId === null || requestParameters.bookId === undefined) {
            throw new runtime.RequiredError('bookId','Required parameter requestParameters.bookId was null or undefined when calling apiV2BookBookIdAuthorsPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v2/book/{book_id}/authors`.replace(`{${"book_id"}}`, encodeURIComponent(String(requestParameters.bookId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject4ToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InlineResponse2002BookAuthorsFromJSON));
    }

    /**
     * ブックの著者を更新します。 教員または管理者でなければなりません。 教員は自身の著作のブックでなければなりません。
     * ブックの著者の更新
     */
    async apiV2BookBookIdAuthorsPut(requestParameters: ApiV2BookBookIdAuthorsPutRequest): Promise<Array<InlineResponse2002BookAuthors>> {
        const response = await this.apiV2BookBookIdAuthorsPutRaw(requestParameters);
        return await response.value();
    }

    /**
     * ブックを削除します。 教員または管理者でなければなりません。 教員は自身の著作のブックでなければなりません。
     * ブックの削除
     */
    async apiV2BookBookIdDeleteRaw(requestParameters: ApiV2BookBookIdDeleteRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.bookId === null || requestParameters.bookId === undefined) {
            throw new runtime.RequiredError('bookId','Required parameter requestParameters.bookId was null or undefined when calling apiV2BookBookIdDelete.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/book/{book_id}`.replace(`{${"book_id"}}`, encodeURIComponent(String(requestParameters.bookId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ブックを削除します。 教員または管理者でなければなりません。 教員は自身の著作のブックでなければなりません。
     * ブックの削除
     */
    async apiV2BookBookIdDelete(requestParameters: ApiV2BookBookIdDeleteRequest): Promise<void> {
        await this.apiV2BookBookIdDeleteRaw(requestParameters);
    }

    /**
     * ブックの詳細を取得します。 教員または管理者いずれでもない場合、LTIリソースとしてリンクされているブックでなければなりません。
     * ブックの取得
     */
    async apiV2BookBookIdGetRaw(requestParameters: ApiV2BookBookIdGetRequest): Promise<runtime.ApiResponse<InlineResponse2005Books>> {
        if (requestParameters.bookId === null || requestParameters.bookId === undefined) {
            throw new runtime.RequiredError('bookId','Required parameter requestParameters.bookId was null or undefined when calling apiV2BookBookIdGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/book/{book_id}`.replace(`{${"book_id"}}`, encodeURIComponent(String(requestParameters.bookId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2005BooksFromJSON(jsonValue));
    }

    /**
     * ブックの詳細を取得します。 教員または管理者いずれでもない場合、LTIリソースとしてリンクされているブックでなければなりません。
     * ブックの取得
     */
    async apiV2BookBookIdGet(requestParameters: ApiV2BookBookIdGetRequest): Promise<InlineResponse2005Books> {
        const response = await this.apiV2BookBookIdGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * ブックを更新します。 教員または管理者でなければなりません。 教員は自身の著作のブックでなければなりません。
     * ブックの更新
     */
    async apiV2BookBookIdPutRaw(requestParameters: ApiV2BookBookIdPutRequest): Promise<runtime.ApiResponse<InlineResponse2005Books>> {
        if (requestParameters.bookId === null || requestParameters.bookId === undefined) {
            throw new runtime.RequiredError('bookId','Required parameter requestParameters.bookId was null or undefined when calling apiV2BookBookIdPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v2/book/{book_id}`.replace(`{${"book_id"}}`, encodeURIComponent(String(requestParameters.bookId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject2ToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2005BooksFromJSON(jsonValue));
    }

    /**
     * ブックを更新します。 教員または管理者でなければなりません。 教員は自身の著作のブックでなければなりません。
     * ブックの更新
     */
    async apiV2BookBookIdPut(requestParameters: ApiV2BookBookIdPutRequest): Promise<InlineResponse2005Books> {
        const response = await this.apiV2BookBookIdPutRaw(requestParameters);
        return await response.value();
    }

    /**
     * ブックを作成します。 教員または管理者でなければなりません。
     * ブックの作成
     */
    async apiV2BookPostRaw(requestParameters: ApiV2BookPostRequest): Promise<runtime.ApiResponse<InlineResponse2005Books>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v2/book`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject3ToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2005BooksFromJSON(jsonValue));
    }

    /**
     * ブックを作成します。 教員または管理者でなければなりません。
     * ブックの作成
     */
    async apiV2BookPost(requestParameters: ApiV2BookPostRequest): Promise<InlineResponse2005Books> {
        const response = await this.apiV2BookPostRaw(requestParameters);
        return await response.value();
    }

    /**
     * 公開ブックの詳細を取得します。
     * 公開ブックの取得
     */
    async apiV2BookPublicTokenGetRaw(requestParameters: ApiV2BookPublicTokenGetRequest): Promise<runtime.ApiResponse<InlineResponse2005Books>> {
        if (requestParameters.token === null || requestParameters.token === undefined) {
            throw new runtime.RequiredError('token','Required parameter requestParameters.token was null or undefined when calling apiV2BookPublicTokenGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.originreferer !== undefined && requestParameters.originreferer !== null) {
            headerParameters['originreferer'] = String(requestParameters.originreferer);
        }

        const response = await this.request({
            path: `/api/v2/book/public/{token}`.replace(`{${"token"}}`, encodeURIComponent(String(requestParameters.token))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2005BooksFromJSON(jsonValue));
    }

    /**
     * 公開ブックの詳細を取得します。
     * 公開ブックの取得
     */
    async apiV2BookPublicTokenGet(requestParameters: ApiV2BookPublicTokenGetRequest): Promise<InlineResponse2005Books> {
        const response = await this.apiV2BookPublicTokenGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * zoom連携ブックのリダイレクト先を取得します。
     * zoom連携ブックの取得
     */
    async apiV2BookZoomMeetingIdGetRaw(requestParameters: ApiV2BookZoomMeetingIdGetRequest): Promise<runtime.ApiResponse<InlineResponse2009>> {
        if (requestParameters.meetingId === null || requestParameters.meetingId === undefined) {
            throw new runtime.RequiredError('meetingId','Required parameter requestParameters.meetingId was null or undefined when calling apiV2BookZoomMeetingIdGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/book/zoom/{meetingId}`.replace(`{${"meetingId"}}`, encodeURIComponent(String(requestParameters.meetingId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2009FromJSON(jsonValue));
    }

    /**
     * zoom連携ブックのリダイレクト先を取得します。
     * zoom連携ブックの取得
     */
    async apiV2BookZoomMeetingIdGet(requestParameters: ApiV2BookZoomMeetingIdGetRequest): Promise<InlineResponse2009> {
        const response = await this.apiV2BookZoomMeetingIdGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * ブックの一覧を取得します。 教員または管理者でなければなりません。
     * ブック一覧 (非推奨)
     */
    async apiV2BooksGetRaw(requestParameters: ApiV2BooksGetRequest): Promise<runtime.ApiResponse<InlineResponse20010>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.sort !== undefined) {
            queryParameters['sort'] = requestParameters.sort;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.perPage !== undefined) {
            queryParameters['per_page'] = requestParameters.perPage;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/books`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse20010FromJSON(jsonValue));
    }

    /**
     * ブックの一覧を取得します。 教員または管理者でなければなりません。
     * ブック一覧 (非推奨)
     */
    async apiV2BooksGet(requestParameters: ApiV2BooksGetRequest): Promise<InlineResponse20010> {
        const response = await this.apiV2BooksGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * ブックをインポートします。 教員または管理者でなければなりません。
     * ブックのインポート
     */
    async apiV2BooksImportPostRaw(requestParameters: ApiV2BooksImportPostRequest): Promise<runtime.ApiResponse<InlineResponse201>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v2/books/import`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject5ToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse201FromJSON(jsonValue));
    }

    /**
     * ブックをインポートします。 教員または管理者でなければなりません。
     * ブックのインポート
     */
    async apiV2BooksImportPost(requestParameters: ApiV2BooksImportPostRequest): Promise<InlineResponse201> {
        const response = await this.apiV2BooksImportPostRaw(requestParameters);
        return await response.value();
    }

    /**
     * ビデオプレイヤーのイベント情報を記録します。 利用は推奨しません。 以前のバージョンv1の構造を踏襲してますが、今後変更される可能性があります。
     * ビデオプレイヤーのイベント情報を記録 (v1互換)
     */
    async apiV2EventPostRaw(requestParameters: ApiV2EventPostRequest): Promise<runtime.ApiResponse<void>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v2/event`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject11ToJSON(requestParameters.body),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ビデオプレイヤーのイベント情報を記録します。 利用は推奨しません。 以前のバージョンv1の構造を踏襲してますが、今後変更される可能性があります。
     * ビデオプレイヤーのイベント情報を記録 (v1互換)
     */
    async apiV2EventPost(requestParameters: ApiV2EventPostRequest): Promise<void> {
        await this.apiV2EventPostRaw(requestParameters);
    }

    /**
     * LTIツールとして起動するためのエンドポイントです。 このエンドポイントをLMSのLTIツールのリダイレクトURIに指定して利用します。 成功時 http://localhost:3000/ にリダイレクトします。
     * LTI v1.3 リダイレクトURI
     */
    async apiV2LtiCallbackPostRaw(requestParameters: ApiV2LtiCallbackPostRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.state === null || requestParameters.state === undefined) {
            throw new runtime.RequiredError('state','Required parameter requestParameters.state was null or undefined when calling apiV2LtiCallbackPost.');
        }

        if (requestParameters.idToken === null || requestParameters.idToken === undefined) {
            throw new runtime.RequiredError('idToken','Required parameter requestParameters.idToken was null or undefined when calling apiV2LtiCallbackPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.state !== undefined) {
            formParams.append('state', requestParameters.state as any);
        }

        if (requestParameters.idToken !== undefined) {
            formParams.append('id_token', requestParameters.idToken as any);
        }

        const response = await this.request({
            path: `/api/v2/lti/callback`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * LTIツールとして起動するためのエンドポイントです。 このエンドポイントをLMSのLTIツールのリダイレクトURIに指定して利用します。 成功時 http://localhost:3000/ にリダイレクトします。
     * LTI v1.3 リダイレクトURI
     */
    async apiV2LtiCallbackPost(requestParameters: ApiV2LtiCallbackPostRequest): Promise<void> {
        await this.apiV2LtiCallbackPostRaw(requestParameters);
    }

    /**
     * LMSの一覧を取得します。 教員または管理者でなければなりません。
     * LMS一覧
     */
    async apiV2LtiClientsGetRaw(): Promise<runtime.ApiResponse<InlineResponse200>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/lti/clients`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse200FromJSON(jsonValue));
    }

    /**
     * LMSの一覧を取得します。 教員または管理者でなければなりません。
     * LMS一覧
     */
    async apiV2LtiClientsGet(): Promise<InlineResponse200> {
        const response = await this.apiV2LtiClientsGetRaw();
        return await response.value();
    }

    /**
     * クライアント認証用の公開鍵を取得するためのエンドポイントです。 このエンドポイントをLTIツールのJWKSエンドポイントとして指定して利用します。
     * LTI JWKS エンドポイント
     */
    async apiV2LtiKeysGetRaw(): Promise<runtime.ApiResponse<InlineResponse2001>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/lti/keys`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2001FromJSON(jsonValue));
    }

    /**
     * クライアント認証用の公開鍵を取得するためのエンドポイントです。 このエンドポイントをLTIツールのJWKSエンドポイントとして指定して利用します。
     * LTI JWKS エンドポイント
     */
    async apiV2LtiKeysGet(): Promise<InlineResponse2001> {
        const response = await this.apiV2LtiKeysGetRaw();
        return await response.value();
    }

    /**
     * LTI v1.1 ツールとして起動するためのエンドポイントです。 このエンドポイントをLMSのLTIツールのURLに指定して利用します。 成功時 http://localhost:3000/ にリダイレクトします。
     * LTI v1.1 起動エンドポイント (非推奨)
     */
    async apiV2LtiLaunchPostRaw(requestParameters: ApiV2LtiLaunchPostRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.oauthVersion === null || requestParameters.oauthVersion === undefined) {
            throw new runtime.RequiredError('oauthVersion','Required parameter requestParameters.oauthVersion was null or undefined when calling apiV2LtiLaunchPost.');
        }

        if (requestParameters.oauthNonce === null || requestParameters.oauthNonce === undefined) {
            throw new runtime.RequiredError('oauthNonce','Required parameter requestParameters.oauthNonce was null or undefined when calling apiV2LtiLaunchPost.');
        }

        if (requestParameters.oauthTimestamp === null || requestParameters.oauthTimestamp === undefined) {
            throw new runtime.RequiredError('oauthTimestamp','Required parameter requestParameters.oauthTimestamp was null or undefined when calling apiV2LtiLaunchPost.');
        }

        if (requestParameters.oauthConsumerKey === null || requestParameters.oauthConsumerKey === undefined) {
            throw new runtime.RequiredError('oauthConsumerKey','Required parameter requestParameters.oauthConsumerKey was null or undefined when calling apiV2LtiLaunchPost.');
        }

        if (requestParameters.oauthSignatureMethod === null || requestParameters.oauthSignatureMethod === undefined) {
            throw new runtime.RequiredError('oauthSignatureMethod','Required parameter requestParameters.oauthSignatureMethod was null or undefined when calling apiV2LtiLaunchPost.');
        }

        if (requestParameters.oauthSignature === null || requestParameters.oauthSignature === undefined) {
            throw new runtime.RequiredError('oauthSignature','Required parameter requestParameters.oauthSignature was null or undefined when calling apiV2LtiLaunchPost.');
        }

        if (requestParameters.ltiMessageType === null || requestParameters.ltiMessageType === undefined) {
            throw new runtime.RequiredError('ltiMessageType','Required parameter requestParameters.ltiMessageType was null or undefined when calling apiV2LtiLaunchPost.');
        }

        if (requestParameters.ltiVersion === null || requestParameters.ltiVersion === undefined) {
            throw new runtime.RequiredError('ltiVersion','Required parameter requestParameters.ltiVersion was null or undefined when calling apiV2LtiLaunchPost.');
        }

        if (requestParameters.resourceLinkId === null || requestParameters.resourceLinkId === undefined) {
            throw new runtime.RequiredError('resourceLinkId','Required parameter requestParameters.resourceLinkId was null or undefined when calling apiV2LtiLaunchPost.');
        }

        if (requestParameters.userId === null || requestParameters.userId === undefined) {
            throw new runtime.RequiredError('userId','Required parameter requestParameters.userId was null or undefined when calling apiV2LtiLaunchPost.');
        }

        if (requestParameters.roles === null || requestParameters.roles === undefined) {
            throw new runtime.RequiredError('roles','Required parameter requestParameters.roles was null or undefined when calling apiV2LtiLaunchPost.');
        }

        if (requestParameters.contextId === null || requestParameters.contextId === undefined) {
            throw new runtime.RequiredError('contextId','Required parameter requestParameters.contextId was null or undefined when calling apiV2LtiLaunchPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.oauthVersion !== undefined) {
            formParams.append('oauth_version', requestParameters.oauthVersion as any);
        }

        if (requestParameters.oauthNonce !== undefined) {
            formParams.append('oauth_nonce', requestParameters.oauthNonce as any);
        }

        if (requestParameters.oauthTimestamp !== undefined) {
            formParams.append('oauth_timestamp', requestParameters.oauthTimestamp as any);
        }

        if (requestParameters.oauthConsumerKey !== undefined) {
            formParams.append('oauth_consumer_key', requestParameters.oauthConsumerKey as any);
        }

        if (requestParameters.oauthSignatureMethod !== undefined) {
            formParams.append('oauth_signature_method', requestParameters.oauthSignatureMethod as any);
        }

        if (requestParameters.oauthSignature !== undefined) {
            formParams.append('oauth_signature', requestParameters.oauthSignature as any);
        }

        if (requestParameters.ltiMessageType !== undefined) {
            formParams.append('lti_message_type', requestParameters.ltiMessageType as any);
        }

        if (requestParameters.ltiVersion !== undefined) {
            formParams.append('lti_version', requestParameters.ltiVersion as any);
        }

        if (requestParameters.resourceLinkId !== undefined) {
            formParams.append('resource_link_id', requestParameters.resourceLinkId as any);
        }

        if (requestParameters.userId !== undefined) {
            formParams.append('user_id', requestParameters.userId as any);
        }

        if (requestParameters.roles !== undefined) {
            formParams.append('roles', requestParameters.roles as any);
        }

        if (requestParameters.contextId !== undefined) {
            formParams.append('context_id', requestParameters.contextId as any);
        }

        if (requestParameters.resourceLinkTitle !== undefined) {
            formParams.append('resource_link_title', requestParameters.resourceLinkTitle as any);
        }

        if (requestParameters.contextTitle !== undefined) {
            formParams.append('context_title', requestParameters.contextTitle as any);
        }

        if (requestParameters.contextLabel !== undefined) {
            formParams.append('context_label', requestParameters.contextLabel as any);
        }

        if (requestParameters.lisPersonNameFull !== undefined) {
            formParams.append('lis_person_name_full', requestParameters.lisPersonNameFull as any);
        }

        if (requestParameters.lisPersonContactEmailPrimary !== undefined) {
            formParams.append('lis_person_contact_email_primary', requestParameters.lisPersonContactEmailPrimary as any);
        }

        if (requestParameters.launchPresentationReturnUrl !== undefined) {
            formParams.append('launch_presentation_return_url', requestParameters.launchPresentationReturnUrl as any);
        }

        const response = await this.request({
            path: `/api/v2/lti/launch`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * LTI v1.1 ツールとして起動するためのエンドポイントです。 このエンドポイントをLMSのLTIツールのURLに指定して利用します。 成功時 http://localhost:3000/ にリダイレクトします。
     * LTI v1.1 起動エンドポイント (非推奨)
     */
    async apiV2LtiLaunchPost(requestParameters: ApiV2LtiLaunchPostRequest): Promise<void> {
        await this.apiV2LtiLaunchPostRaw(requestParameters);
    }

    /**
     * LTIツールとして起動するためのエンドポイントです。 このエンドポイントをLMSのLTIツールのログイン初期化エンドポイントに指定して利用します。 Authorizationエンドポイントにリダイレクトします。
     * LTI v1.3 ログイン初期化エンドポイント
     */
    async apiV2LtiLoginGetRaw(requestParameters: ApiV2LtiLoginGetRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.iss === null || requestParameters.iss === undefined) {
            throw new runtime.RequiredError('iss','Required parameter requestParameters.iss was null or undefined when calling apiV2LtiLoginGet.');
        }

        if (requestParameters.loginHint === null || requestParameters.loginHint === undefined) {
            throw new runtime.RequiredError('loginHint','Required parameter requestParameters.loginHint was null or undefined when calling apiV2LtiLoginGet.');
        }

        if (requestParameters.targetLinkUri === null || requestParameters.targetLinkUri === undefined) {
            throw new runtime.RequiredError('targetLinkUri','Required parameter requestParameters.targetLinkUri was null or undefined when calling apiV2LtiLoginGet.');
        }

        if (requestParameters.clientId === null || requestParameters.clientId === undefined) {
            throw new runtime.RequiredError('clientId','Required parameter requestParameters.clientId was null or undefined when calling apiV2LtiLoginGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.iss !== undefined) {
            queryParameters['iss'] = requestParameters.iss;
        }

        if (requestParameters.loginHint !== undefined) {
            queryParameters['login_hint'] = requestParameters.loginHint;
        }

        if (requestParameters.targetLinkUri !== undefined) {
            queryParameters['target_link_uri'] = requestParameters.targetLinkUri;
        }

        if (requestParameters.ltiMessageHint !== undefined) {
            queryParameters['lti_message_hint'] = requestParameters.ltiMessageHint;
        }

        if (requestParameters.ltiDeploymentId !== undefined) {
            queryParameters['lti_deployment_id'] = requestParameters.ltiDeploymentId;
        }

        if (requestParameters.clientId !== undefined) {
            queryParameters['client_id'] = requestParameters.clientId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/lti/login`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * LTIツールとして起動するためのエンドポイントです。 このエンドポイントをLMSのLTIツールのログイン初期化エンドポイントに指定して利用します。 Authorizationエンドポイントにリダイレクトします。
     * LTI v1.3 ログイン初期化エンドポイント
     */
    async apiV2LtiLoginGet(requestParameters: ApiV2LtiLoginGetRequest): Promise<void> {
        await this.apiV2LtiLoginGetRaw(requestParameters);
    }

    /**
     * LTIツールとして起動するためのエンドポイントです。 このエンドポイントをLMSのLTIツールのログイン初期化エンドポイントに指定して利用します。 Authorizationエンドポイントにリダイレクトします。
     * LTI v1.3 ログイン初期化エンドポイント
     */
    async apiV2LtiLoginPostRaw(requestParameters: ApiV2LtiLoginPostRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.iss === null || requestParameters.iss === undefined) {
            throw new runtime.RequiredError('iss','Required parameter requestParameters.iss was null or undefined when calling apiV2LtiLoginPost.');
        }

        if (requestParameters.loginHint === null || requestParameters.loginHint === undefined) {
            throw new runtime.RequiredError('loginHint','Required parameter requestParameters.loginHint was null or undefined when calling apiV2LtiLoginPost.');
        }

        if (requestParameters.targetLinkUri === null || requestParameters.targetLinkUri === undefined) {
            throw new runtime.RequiredError('targetLinkUri','Required parameter requestParameters.targetLinkUri was null or undefined when calling apiV2LtiLoginPost.');
        }

        if (requestParameters.clientId === null || requestParameters.clientId === undefined) {
            throw new runtime.RequiredError('clientId','Required parameter requestParameters.clientId was null or undefined when calling apiV2LtiLoginPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.iss !== undefined) {
            formParams.append('iss', requestParameters.iss as any);
        }

        if (requestParameters.loginHint !== undefined) {
            formParams.append('login_hint', requestParameters.loginHint as any);
        }

        if (requestParameters.targetLinkUri !== undefined) {
            formParams.append('target_link_uri', requestParameters.targetLinkUri as any);
        }

        if (requestParameters.ltiMessageHint !== undefined) {
            formParams.append('lti_message_hint', requestParameters.ltiMessageHint as any);
        }

        if (requestParameters.ltiDeploymentId !== undefined) {
            formParams.append('lti_deployment_id', requestParameters.ltiDeploymentId as any);
        }

        if (requestParameters.clientId !== undefined) {
            formParams.append('client_id', requestParameters.clientId as any);
        }

        const response = await this.request({
            path: `/api/v2/lti/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * LTIツールとして起動するためのエンドポイントです。 このエンドポイントをLMSのLTIツールのログイン初期化エンドポイントに指定して利用します。 Authorizationエンドポイントにリダイレクトします。
     * LTI v1.3 ログイン初期化エンドポイント
     */
    async apiV2LtiLoginPost(requestParameters: ApiV2LtiLoginPostRequest): Promise<void> {
        await this.apiV2LtiLoginPostRaw(requestParameters);
    }

    /**
     * LTI Resource Linkを削除します。 教員または管理者でなければなりません。
     * LTI Resource Linkの削除
     */
    async apiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdDeleteRaw(requestParameters: ApiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdDeleteRequest): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.ltiConsumerId === null || requestParameters.ltiConsumerId === undefined) {
            throw new runtime.RequiredError('ltiConsumerId','Required parameter requestParameters.ltiConsumerId was null or undefined when calling apiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdDelete.');
        }

        if (requestParameters.ltiResourceLinkId === null || requestParameters.ltiResourceLinkId === undefined) {
            throw new runtime.RequiredError('ltiResourceLinkId','Required parameter requestParameters.ltiResourceLinkId was null or undefined when calling apiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdDelete.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/lti/{lti_consumer_id}/resource_link/{lti_resource_link_id}`.replace(`{${"lti_consumer_id"}}`, encodeURIComponent(String(requestParameters.ltiConsumerId))).replace(`{${"lti_resource_link_id"}}`, encodeURIComponent(String(requestParameters.ltiResourceLinkId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * LTI Resource Linkを削除します。 教員または管理者でなければなりません。
     * LTI Resource Linkの削除
     */
    async apiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdDelete(requestParameters: ApiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdDeleteRequest): Promise<object> {
        const response = await this.apiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdDeleteRaw(requestParameters);
        return await response.value();
    }

    /**
     * LTI Resource Linkの詳細を取得します。 教員または管理者でなければなりません。
     * LTI Resource Linkの取得
     */
    async apiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdGetRaw(requestParameters: ApiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdGetRequest): Promise<runtime.ApiResponse<InlineResponse2003>> {
        if (requestParameters.ltiConsumerId === null || requestParameters.ltiConsumerId === undefined) {
            throw new runtime.RequiredError('ltiConsumerId','Required parameter requestParameters.ltiConsumerId was null or undefined when calling apiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdGet.');
        }

        if (requestParameters.ltiResourceLinkId === null || requestParameters.ltiResourceLinkId === undefined) {
            throw new runtime.RequiredError('ltiResourceLinkId','Required parameter requestParameters.ltiResourceLinkId was null or undefined when calling apiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/lti/{lti_consumer_id}/resource_link/{lti_resource_link_id}`.replace(`{${"lti_consumer_id"}}`, encodeURIComponent(String(requestParameters.ltiConsumerId))).replace(`{${"lti_resource_link_id"}}`, encodeURIComponent(String(requestParameters.ltiResourceLinkId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2003FromJSON(jsonValue));
    }

    /**
     * LTI Resource Linkの詳細を取得します。 教員または管理者でなければなりません。
     * LTI Resource Linkの取得
     */
    async apiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdGet(requestParameters: ApiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdGetRequest): Promise<InlineResponse2003> {
        const response = await this.apiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * LTI Resource Linkを更新します。 教員または管理者でなければなりません。
     * LTI Resource Linkの更新
     */
    async apiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdPutRaw(requestParameters: ApiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdPutRequest): Promise<runtime.ApiResponse<InlineResponse2003>> {
        if (requestParameters.ltiConsumerId === null || requestParameters.ltiConsumerId === undefined) {
            throw new runtime.RequiredError('ltiConsumerId','Required parameter requestParameters.ltiConsumerId was null or undefined when calling apiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdPut.');
        }

        if (requestParameters.ltiResourceLinkId === null || requestParameters.ltiResourceLinkId === undefined) {
            throw new runtime.RequiredError('ltiResourceLinkId','Required parameter requestParameters.ltiResourceLinkId was null or undefined when calling apiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v2/lti/{lti_consumer_id}/resource_link/{lti_resource_link_id}`.replace(`{${"lti_consumer_id"}}`, encodeURIComponent(String(requestParameters.ltiConsumerId))).replace(`{${"lti_resource_link_id"}}`, encodeURIComponent(String(requestParameters.ltiResourceLinkId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObjectToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2003FromJSON(jsonValue));
    }

    /**
     * LTI Resource Linkを更新します。 教員または管理者でなければなりません。
     * LTI Resource Linkの更新
     */
    async apiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdPut(requestParameters: ApiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdPutRequest): Promise<InlineResponse2003> {
        const response = await this.apiV2LtiLtiConsumerIdResourceLinkLtiResourceLinkIdPutRaw(requestParameters);
        return await response.value();
    }

    /**
     * LTIリンクを検索します。 教員または管理者でなければなりません。
     * LTIリンク検索
     */
    async apiV2LtiSearchGetRaw(requestParameters: ApiV2LtiSearchGetRequest): Promise<runtime.ApiResponse<InlineResponse2002>> {
        if (requestParameters.q === null || requestParameters.q === undefined) {
            throw new runtime.RequiredError('q','Required parameter requestParameters.q was null or undefined when calling apiV2LtiSearchGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.q !== undefined) {
            queryParameters['q'] = requestParameters.q;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['sort'] = requestParameters.sort;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.perPage !== undefined) {
            queryParameters['per_page'] = requestParameters.perPage;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/lti/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2002FromJSON(jsonValue));
    }

    /**
     * LTIリンクを検索します。 教員または管理者でなければなりません。
     * LTIリンク検索
     */
    async apiV2LtiSearchGet(requestParameters: ApiV2LtiSearchGetRequest): Promise<InlineResponse2002> {
        const response = await this.apiV2LtiSearchGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * リソースの埋め込み情報を取得します。 教員または管理者でなければなりません。
     * リソースの埋め込み情報の取得
     */
    async apiV2ResourceResourceIdOembedGetRaw(requestParameters: ApiV2ResourceResourceIdOembedGetRequest): Promise<runtime.ApiResponse<InlineResponse20013>> {
        if (requestParameters.resourceId === null || requestParameters.resourceId === undefined) {
            throw new runtime.RequiredError('resourceId','Required parameter requestParameters.resourceId was null or undefined when calling apiV2ResourceResourceIdOembedGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/resource/{resource_id}/oembed`.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters.resourceId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse20013FromJSON(jsonValue));
    }

    /**
     * リソースの埋め込み情報を取得します。 教員または管理者でなければなりません。
     * リソースの埋め込み情報の取得
     */
    async apiV2ResourceResourceIdOembedGet(requestParameters: ApiV2ResourceResourceIdOembedGetRequest): Promise<InlineResponse20013> {
        const response = await this.apiV2ResourceResourceIdOembedGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * 字幕をアップロードします。 教員または管理者でなければなりません。
     * 字幕のアップロード
     */
    async apiV2ResourceResourceIdVideoTrackPostRaw(requestParameters: ApiV2ResourceResourceIdVideoTrackPostRequest): Promise<runtime.ApiResponse<InlineResponse2004ResourceTracks>> {
        if (requestParameters.resourceId === null || requestParameters.resourceId === undefined) {
            throw new runtime.RequiredError('resourceId','Required parameter requestParameters.resourceId was null or undefined when calling apiV2ResourceResourceIdVideoTrackPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v2/resource/{resource_id}/video_track`.replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters.resourceId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject10ToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2004ResourceTracksFromJSON(jsonValue));
    }

    /**
     * 字幕をアップロードします。 教員または管理者でなければなりません。
     * 字幕のアップロード
     */
    async apiV2ResourceResourceIdVideoTrackPost(requestParameters: ApiV2ResourceResourceIdVideoTrackPostRequest): Promise<InlineResponse2004ResourceTracks> {
        const response = await this.apiV2ResourceResourceIdVideoTrackPostRaw(requestParameters);
        return await response.value();
    }

    /**
     * 字幕を削除します。 教員または管理者でなければなりません。
     * 字幕の削除
     */
    async apiV2ResourceResourceIdVideoTrackVideoTrackIdDeleteRaw(requestParameters: ApiV2ResourceResourceIdVideoTrackVideoTrackIdDeleteRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.videoTrackId === null || requestParameters.videoTrackId === undefined) {
            throw new runtime.RequiredError('videoTrackId','Required parameter requestParameters.videoTrackId was null or undefined when calling apiV2ResourceResourceIdVideoTrackVideoTrackIdDelete.');
        }

        if (requestParameters.resourceId === null || requestParameters.resourceId === undefined) {
            throw new runtime.RequiredError('resourceId','Required parameter requestParameters.resourceId was null or undefined when calling apiV2ResourceResourceIdVideoTrackVideoTrackIdDelete.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/resource/{resource_id}/video_track/{video_track_id}`.replace(`{${"video_track_id"}}`, encodeURIComponent(String(requestParameters.videoTrackId))).replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters.resourceId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 字幕を削除します。 教員または管理者でなければなりません。
     * 字幕の削除
     */
    async apiV2ResourceResourceIdVideoTrackVideoTrackIdDelete(requestParameters: ApiV2ResourceResourceIdVideoTrackVideoTrackIdDeleteRequest): Promise<void> {
        await this.apiV2ResourceResourceIdVideoTrackVideoTrackIdDeleteRaw(requestParameters);
    }

    /**
     * 字幕を取得します。
     * 字幕の取得
     */
    async apiV2ResourceResourceIdVideoTrackVideoTrackIdVttGetRaw(requestParameters: ApiV2ResourceResourceIdVideoTrackVideoTrackIdVttGetRequest): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.accessToken === null || requestParameters.accessToken === undefined) {
            throw new runtime.RequiredError('accessToken','Required parameter requestParameters.accessToken was null or undefined when calling apiV2ResourceResourceIdVideoTrackVideoTrackIdVttGet.');
        }

        if (requestParameters.videoTrackId === null || requestParameters.videoTrackId === undefined) {
            throw new runtime.RequiredError('videoTrackId','Required parameter requestParameters.videoTrackId was null or undefined when calling apiV2ResourceResourceIdVideoTrackVideoTrackIdVttGet.');
        }

        if (requestParameters.resourceId === null || requestParameters.resourceId === undefined) {
            throw new runtime.RequiredError('resourceId','Required parameter requestParameters.resourceId was null or undefined when calling apiV2ResourceResourceIdVideoTrackVideoTrackIdVttGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.accessToken !== undefined) {
            queryParameters['accessToken'] = requestParameters.accessToken;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/resource/{resource_id}/video_track/{video_track_id}/vtt`.replace(`{${"video_track_id"}}`, encodeURIComponent(String(requestParameters.videoTrackId))).replace(`{${"resource_id"}}`, encodeURIComponent(String(requestParameters.resourceId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * 字幕を取得します。
     * 字幕の取得
     */
    async apiV2ResourceResourceIdVideoTrackVideoTrackIdVttGet(requestParameters: ApiV2ResourceResourceIdVideoTrackVideoTrackIdVttGetRequest): Promise<object> {
        const response = await this.apiV2ResourceResourceIdVideoTrackVideoTrackIdVttGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * リソースの一覧を取得します。 教員または管理者でなければなりません。
     * リソース一覧 (非推奨)
     */
    async apiV2ResourcesGetRaw(requestParameters: ApiV2ResourcesGetRequest): Promise<runtime.ApiResponse<InlineResponse20012>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.sort !== undefined) {
            queryParameters['sort'] = requestParameters.sort;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.perPage !== undefined) {
            queryParameters['per_page'] = requestParameters.perPage;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/resources`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse20012FromJSON(jsonValue));
    }

    /**
     * リソースの一覧を取得します。 教員または管理者でなければなりません。
     * リソース一覧 (非推奨)
     */
    async apiV2ResourcesGet(requestParameters: ApiV2ResourcesGetRequest): Promise<InlineResponse20012> {
        const response = await this.apiV2ResourcesGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * コンテンツを検索します。 教員または管理者でなければなりません。
     * コンテンツ検索
     */
    async apiV2SearchGetRaw(requestParameters: ApiV2SearchGetRequest): Promise<runtime.ApiResponse<InlineResponse2004>> {
        if (requestParameters.type === null || requestParameters.type === undefined) {
            throw new runtime.RequiredError('type','Required parameter requestParameters.type was null or undefined when calling apiV2SearchGet.');
        }

        if (requestParameters.q === null || requestParameters.q === undefined) {
            throw new runtime.RequiredError('q','Required parameter requestParameters.q was null or undefined when calling apiV2SearchGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.type !== undefined) {
            queryParameters['type'] = requestParameters.type;
        }

        if (requestParameters.q !== undefined) {
            queryParameters['q'] = requestParameters.q;
        }

        if (requestParameters.filter !== undefined) {
            queryParameters['filter'] = requestParameters.filter;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['sort'] = requestParameters.sort;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.perPage !== undefined) {
            queryParameters['per_page'] = requestParameters.perPage;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2004FromJSON(jsonValue));
    }

    /**
     * コンテンツを検索します。 教員または管理者でなければなりません。
     * コンテンツ検索
     */
    async apiV2SearchGet(requestParameters: ApiV2SearchGetRequest): Promise<InlineResponse2004> {
        const response = await this.apiV2SearchGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * 自身に関する詳細な情報を取得します。
     * セッション情報
     */
    async apiV2SessionGetRaw(): Promise<runtime.ApiResponse<{ [key: string]: object; }>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/session`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * 自身に関する詳細な情報を取得します。
     * セッション情報
     */
    async apiV2SessionGet(): Promise<{ [key: string]: object; }> {
        const response = await this.apiV2SessionGetRaw();
        return await response.value();
    }

    /**
     * トピックを作成します。 教員または管理者でなければなりません。
     * トピックの作成
     */
    async apiV2TopicPostRaw(requestParameters: ApiV2TopicPostRequest): Promise<runtime.ApiResponse<InlineResponse2004Topics>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v2/topic`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject7ToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2004TopicsFromJSON(jsonValue));
    }

    /**
     * トピックを作成します。 教員または管理者でなければなりません。
     * トピックの作成
     */
    async apiV2TopicPost(requestParameters: ApiV2TopicPostRequest): Promise<InlineResponse2004Topics> {
        const response = await this.apiV2TopicPostRaw(requestParameters);
        return await response.value();
    }

    /**
     * 自身の学習活動を更新します。
     * 学習活動の更新
     */
    async apiV2TopicTopicIdActivityPutRaw(requestParameters: ApiV2TopicTopicIdActivityPutRequest): Promise<runtime.ApiResponse<{ [key: string]: object; }>> {
        if (requestParameters.topicId === null || requestParameters.topicId === undefined) {
            throw new runtime.RequiredError('topicId','Required parameter requestParameters.topicId was null or undefined when calling apiV2TopicTopicIdActivityPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.currentLtiContextOnly !== undefined) {
            queryParameters['current_lti_context_only'] = requestParameters.currentLtiContextOnly;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v2/topic/{topic_id}/activity`.replace(`{${"topic_id"}}`, encodeURIComponent(String(requestParameters.topicId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject8ToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * 自身の学習活動を更新します。
     * 学習活動の更新
     */
    async apiV2TopicTopicIdActivityPut(requestParameters: ApiV2TopicTopicIdActivityPutRequest): Promise<{ [key: string]: object; }> {
        const response = await this.apiV2TopicTopicIdActivityPutRaw(requestParameters);
        return await response.value();
    }

    /**
     * トピックの著者を更新します。 教員または管理者でなければなりません。 教員は自身の著作のトピックでなければなりません。
     * トピックの著者の更新
     */
    async apiV2TopicTopicIdAuthorsPutRaw(requestParameters: ApiV2TopicTopicIdAuthorsPutRequest): Promise<runtime.ApiResponse<Array<InlineResponse2002BookAuthors>>> {
        if (requestParameters.topicId === null || requestParameters.topicId === undefined) {
            throw new runtime.RequiredError('topicId','Required parameter requestParameters.topicId was null or undefined when calling apiV2TopicTopicIdAuthorsPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v2/topic/{topic_id}/authors`.replace(`{${"topic_id"}}`, encodeURIComponent(String(requestParameters.topicId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject9ToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InlineResponse2002BookAuthorsFromJSON));
    }

    /**
     * トピックの著者を更新します。 教員または管理者でなければなりません。 教員は自身の著作のトピックでなければなりません。
     * トピックの著者の更新
     */
    async apiV2TopicTopicIdAuthorsPut(requestParameters: ApiV2TopicTopicIdAuthorsPutRequest): Promise<Array<InlineResponse2002BookAuthors>> {
        const response = await this.apiV2TopicTopicIdAuthorsPutRaw(requestParameters);
        return await response.value();
    }

    /**
     * トピックを削除します。 ブックから参照されている場合、そのブックから取り除きます。 教員または管理者でなければなりません。 教員は自身の著作のトピックでなければなりません。
     * トピックの削除
     */
    async apiV2TopicTopicIdDeleteRaw(requestParameters: ApiV2TopicTopicIdDeleteRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.topicId === null || requestParameters.topicId === undefined) {
            throw new runtime.RequiredError('topicId','Required parameter requestParameters.topicId was null or undefined when calling apiV2TopicTopicIdDelete.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/topic/{topic_id}`.replace(`{${"topic_id"}}`, encodeURIComponent(String(requestParameters.topicId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * トピックを削除します。 ブックから参照されている場合、そのブックから取り除きます。 教員または管理者でなければなりません。 教員は自身の著作のトピックでなければなりません。
     * トピックの削除
     */
    async apiV2TopicTopicIdDelete(requestParameters: ApiV2TopicTopicIdDeleteRequest): Promise<void> {
        await this.apiV2TopicTopicIdDeleteRaw(requestParameters);
    }

    /**
     * トピックの詳細を取得します。 教員または管理者でなければなりません。
     * トピックの取得
     */
    async apiV2TopicTopicIdGetRaw(requestParameters: ApiV2TopicTopicIdGetRequest): Promise<runtime.ApiResponse<InlineResponse2004Topics>> {
        if (requestParameters.topicId === null || requestParameters.topicId === undefined) {
            throw new runtime.RequiredError('topicId','Required parameter requestParameters.topicId was null or undefined when calling apiV2TopicTopicIdGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/topic/{topic_id}`.replace(`{${"topic_id"}}`, encodeURIComponent(String(requestParameters.topicId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2004TopicsFromJSON(jsonValue));
    }

    /**
     * トピックの詳細を取得します。 教員または管理者でなければなりません。
     * トピックの取得
     */
    async apiV2TopicTopicIdGet(requestParameters: ApiV2TopicTopicIdGetRequest): Promise<InlineResponse2004Topics> {
        const response = await this.apiV2TopicTopicIdGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * トピックを更新します。 教員または管理者でなければなりません。 教員は自身の著作のトピックでなければなりません。
     * トピックの更新
     */
    async apiV2TopicTopicIdPutRaw(requestParameters: ApiV2TopicTopicIdPutRequest): Promise<runtime.ApiResponse<InlineResponse2004Topics>> {
        if (requestParameters.topicId === null || requestParameters.topicId === undefined) {
            throw new runtime.RequiredError('topicId','Required parameter requestParameters.topicId was null or undefined when calling apiV2TopicTopicIdPut.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v2/topic/{topic_id}`.replace(`{${"topic_id"}}`, encodeURIComponent(String(requestParameters.topicId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject6ToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2004TopicsFromJSON(jsonValue));
    }

    /**
     * トピックを更新します。 教員または管理者でなければなりません。 教員は自身の著作のトピックでなければなりません。
     * トピックの更新
     */
    async apiV2TopicTopicIdPut(requestParameters: ApiV2TopicTopicIdPutRequest): Promise<InlineResponse2004Topics> {
        const response = await this.apiV2TopicTopicIdPutRaw(requestParameters);
        return await response.value();
    }

    /**
     * トピックの一覧を取得します。 教員または管理者でなければなりません。
     * トピック一覧 (非推奨)
     */
    async apiV2TopicsGetRaw(requestParameters: ApiV2TopicsGetRequest): Promise<runtime.ApiResponse<InlineResponse20011>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.sort !== undefined) {
            queryParameters['sort'] = requestParameters.sort;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.perPage !== undefined) {
            queryParameters['per_page'] = requestParameters.perPage;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/topics`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse20011FromJSON(jsonValue));
    }

    /**
     * トピックの一覧を取得します。 教員または管理者でなければなりません。
     * トピック一覧 (非推奨)
     */
    async apiV2TopicsGet(requestParameters: ApiV2TopicsGetRequest): Promise<InlineResponse20011> {
        const response = await this.apiV2TopicsGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * ユーザーの設定内容を更新し、セッションとdbに保存します。
     * ユーザー設定値の更新
     */
    async apiV2UserSettingsPutRaw(requestParameters: ApiV2UserSettingsPutRequest): Promise<runtime.ApiResponse<object>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v2/userSettings`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject1ToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * ユーザーの設定内容を更新し、セッションとdbに保存します。
     * ユーザー設定値の更新
     */
    async apiV2UserSettingsPut(requestParameters: ApiV2UserSettingsPutRequest): Promise<object> {
        const response = await this.apiV2UserSettingsPutRaw(requestParameters);
        return await response.value();
    }

    /**
     * 利用者が著者に含まれるブックの一覧を取得します。 教員または管理者でなければなりません。
     * 自分のブックの一覧 (非推奨)
     */
    async apiV2UserUserIdBooksGetRaw(requestParameters: ApiV2UserUserIdBooksGetRequest): Promise<runtime.ApiResponse<InlineResponse2005>> {
        if (requestParameters.userId === null || requestParameters.userId === undefined) {
            throw new runtime.RequiredError('userId','Required parameter requestParameters.userId was null or undefined when calling apiV2UserUserIdBooksGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.sort !== undefined) {
            queryParameters['sort'] = requestParameters.sort;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.perPage !== undefined) {
            queryParameters['per_page'] = requestParameters.perPage;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/user/{user_id}/books`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters.userId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2005FromJSON(jsonValue));
    }

    /**
     * 利用者が著者に含まれるブックの一覧を取得します。 教員または管理者でなければなりません。
     * 自分のブックの一覧 (非推奨)
     */
    async apiV2UserUserIdBooksGet(requestParameters: ApiV2UserUserIdBooksGetRequest): Promise<InlineResponse2005> {
        const response = await this.apiV2UserUserIdBooksGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * 利用者が著者に含まれるトピックの一覧を取得します。 教員または管理者でなければなりません。
     * 自分のトピックの一覧 (非推奨)
     */
    async apiV2UserUserIdTopicsGetRaw(requestParameters: ApiV2UserUserIdTopicsGetRequest): Promise<runtime.ApiResponse<InlineResponse2006>> {
        if (requestParameters.userId === null || requestParameters.userId === undefined) {
            throw new runtime.RequiredError('userId','Required parameter requestParameters.userId was null or undefined when calling apiV2UserUserIdTopicsGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.sort !== undefined) {
            queryParameters['sort'] = requestParameters.sort;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.perPage !== undefined) {
            queryParameters['per_page'] = requestParameters.perPage;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/user/{user_id}/topics`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters.userId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2006FromJSON(jsonValue));
    }

    /**
     * 利用者が著者に含まれるトピックの一覧を取得します。 教員または管理者でなければなりません。
     * 自分のトピックの一覧 (非推奨)
     */
    async apiV2UserUserIdTopicsGet(requestParameters: ApiV2UserUserIdTopicsGetRequest): Promise<InlineResponse2006> {
        const response = await this.apiV2UserUserIdTopicsGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * 利用者に関する詳細な情報を取得します。 教員または管理者でなければなりません。
     * 利用者情報
     */
    async apiV2UsersEmailGetRaw(requestParameters: ApiV2UsersEmailGetRequest): Promise<runtime.ApiResponse<Array<InlineResponse2007>>> {
        if (requestParameters.email === null || requestParameters.email === undefined) {
            throw new runtime.RequiredError('email','Required parameter requestParameters.email was null or undefined when calling apiV2UsersEmailGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/users/{email}`.replace(`{${"email"}}`, encodeURIComponent(String(requestParameters.email))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InlineResponse2007FromJSON));
    }

    /**
     * 利用者に関する詳細な情報を取得します。 教員または管理者でなければなりません。
     * 利用者情報
     */
    async apiV2UsersEmailGet(requestParameters: ApiV2UsersEmailGetRequest): Promise<Array<InlineResponse2007>> {
        const response = await this.apiV2UsersEmailGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * 動画ファイルを与えてアップロードします。 教員または管理者でなければなりません。
     * Wowza Streaming Engine へのアップロードするためのエンドポイント
     */
    async apiV2WowzaPostRaw(): Promise<runtime.ApiResponse<InlineResponse2011>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/wowza`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2011FromJSON(jsonValue));
    }

    /**
     * 動画ファイルを与えてアップロードします。 教員または管理者でなければなりません。
     * Wowza Streaming Engine へのアップロードするためのエンドポイント
     */
    async apiV2WowzaPost(): Promise<InlineResponse2011> {
        const response = await this.apiV2WowzaPostRaw();
        return await response.value();
    }

    /**
     * Wowza Streaming Engine のコンテンツのパスを与えると、 そのコンテンツの playlist.m3u8 ファイルにリダイレクトします。 サーバー管理者によって無効化されている場合 404 を返します。
     * Wowza Streaming Engine にアクセスするためのエンドポイント
     */
    async apiV2WowzaWildcardGetRaw(requestParameters: ApiV2WowzaWildcardGetRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.accessToken === null || requestParameters.accessToken === undefined) {
            throw new runtime.RequiredError('accessToken','Required parameter requestParameters.accessToken was null or undefined when calling apiV2WowzaWildcardGet.');
        }

        if (requestParameters.wildcard === null || requestParameters.wildcard === undefined) {
            throw new runtime.RequiredError('wildcard','Required parameter requestParameters.wildcard was null or undefined when calling apiV2WowzaWildcardGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.accessToken !== undefined) {
            queryParameters['accessToken'] = requestParameters.accessToken;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/wowza/{wildcard}`.replace(`{${"wildcard"}}`, encodeURIComponent(String(requestParameters.wildcard))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Wowza Streaming Engine のコンテンツのパスを与えると、 そのコンテンツの playlist.m3u8 ファイルにリダイレクトします。 サーバー管理者によって無効化されている場合 404 を返します。
     * Wowza Streaming Engine にアクセスするためのエンドポイント
     */
    async apiV2WowzaWildcardGet(requestParameters: ApiV2WowzaWildcardGetRequest): Promise<void> {
        await this.apiV2WowzaWildcardGetRaw(requestParameters);
    }

}

/**
    * @export
    * @enum {string}
    */
export enum ApiV2LtiSearchGetSortEnum {
    created = 'created',
    reverse_created = 'reverse-created',
    updated = 'updated',
    reverse_updated = 'reverse-updated',
    title = 'title',
    reverse_title = 'reverse-title'
}
/**
    * @export
    * @enum {string}
    */
export enum ApiV2SearchGetTypeEnum {
    topic = 'topic',
    book = 'book'
}
/**
    * @export
    * @enum {string}
    */
export enum ApiV2SearchGetFilterEnum {
    all = 'all',
    self = 'self',
    other = 'other'
}
/**
    * @export
    * @enum {string}
    */
export enum ApiV2SearchGetSortEnum {
    updated = 'updated',
    reverse_updated = 'reverse-updated',
    created = 'created',
    reverse_created = 'reverse-created',
    name = 'name',
    reverse_name = 'reverse-name'
}
