/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2BookBookIdTopics
 */
export interface ApiV2BookBookIdTopics {
    /**
     * 
     * @type {number}
     * @memberof ApiV2BookBookIdTopics
     */
    id?: number;
}

export function ApiV2BookBookIdTopicsFromJSON(json: any): ApiV2BookBookIdTopics {
    return ApiV2BookBookIdTopicsFromJSONTyped(json, false);
}

export function ApiV2BookBookIdTopicsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2BookBookIdTopics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function ApiV2BookBookIdTopicsToJSON(value?: ApiV2BookBookIdTopics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


