/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2LtiMembersUserSettings
 */
export interface ApiV2LtiMembersUserSettings {
    /**
     * 
     * @type {boolean}
     * @memberof ApiV2LtiMembersUserSettings
     */
    zoomImportEnabled?: boolean;
}

export function ApiV2LtiMembersUserSettingsFromJSON(json: any): ApiV2LtiMembersUserSettings {
    return ApiV2LtiMembersUserSettingsFromJSONTyped(json, false);
}

export function ApiV2LtiMembersUserSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2LtiMembersUserSettings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'zoomImportEnabled': !exists(json, 'zoomImportEnabled') ? undefined : json['zoomImportEnabled'],
    };
}

export function ApiV2LtiMembersUserSettingsToJSON(value?: ApiV2LtiMembersUserSettings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'zoomImportEnabled': value.zoomImportEnabled,
    };
}


