/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApiV2BookBookIdTopics,
    ApiV2BookBookIdTopicsFromJSON,
    ApiV2BookBookIdTopicsFromJSONTyped,
    ApiV2BookBookIdTopicsToJSON,
} from './';

/**
 * 
 * @export
 * @interface ApiV2BookBookIdSections
 */
export interface ApiV2BookBookIdSections {
    /**
     * 
     * @type {string}
     * @memberof ApiV2BookBookIdSections
     */
    name?: string;
    /**
     * 
     * @type {Array<ApiV2BookBookIdTopics>}
     * @memberof ApiV2BookBookIdSections
     */
    topics?: Array<ApiV2BookBookIdTopics>;
}

export function ApiV2BookBookIdSectionsFromJSON(json: any): ApiV2BookBookIdSections {
    return ApiV2BookBookIdSectionsFromJSONTyped(json, false);
}

export function ApiV2BookBookIdSectionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2BookBookIdSections {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'topics': !exists(json, 'topics') ? undefined : ((json['topics'] as Array<any>).map(ApiV2BookBookIdTopicsFromJSON)),
    };
}

export function ApiV2BookBookIdSectionsToJSON(value?: ApiV2BookBookIdSections | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'topics': value.topics === undefined ? undefined : ((value.topics as Array<any>).map(ApiV2BookBookIdTopicsToJSON)),
    };
}


