/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2TopicTopicIdActivityTimeRanges
 */
export interface ApiV2TopicTopicIdActivityTimeRanges {
    /**
     * 
     * @type {number}
     * @memberof ApiV2TopicTopicIdActivityTimeRanges
     */
    startMs?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2TopicTopicIdActivityTimeRanges
     */
    endMs?: number;
}

export function ApiV2TopicTopicIdActivityTimeRangesFromJSON(json: any): ApiV2TopicTopicIdActivityTimeRanges {
    return ApiV2TopicTopicIdActivityTimeRangesFromJSONTyped(json, false);
}

export function ApiV2TopicTopicIdActivityTimeRangesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2TopicTopicIdActivityTimeRanges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startMs': !exists(json, 'startMs') ? undefined : json['startMs'],
        'endMs': !exists(json, 'endMs') ? undefined : json['endMs'],
    };
}

export function ApiV2TopicTopicIdActivityTimeRangesToJSON(value?: ApiV2TopicTopicIdActivityTimeRanges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startMs': value.startMs,
        'endMs': value.endMs,
    };
}


