/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse20014
 */
export interface InlineResponse20014 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20014
     */
    activityId: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20014
     */
    startMs?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20014
     */
    endMs?: number;
}

export function InlineResponse20014FromJSON(json: any): InlineResponse20014 {
    return InlineResponse20014FromJSONTyped(json, false);
}

export function InlineResponse20014FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20014 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'activityId': json['activityId'],
        'startMs': !exists(json, 'startMs') ? undefined : json['startMs'],
        'endMs': !exists(json, 'endMs') ? undefined : json['endMs'],
    };
}

export function InlineResponse20014ToJSON(value?: InlineResponse20014 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'activityId': value.activityId,
        'startMs': value.startMs,
        'endMs': value.endMs,
    };
}


