/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2004RelatedBooks
 */
export interface InlineResponse2004RelatedBooks {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2004RelatedBooks
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004RelatedBooks
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004RelatedBooks
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004RelatedBooks
     */
    language?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2004RelatedBooks
     */
    shared?: boolean;
}

export function InlineResponse2004RelatedBooksFromJSON(json: any): InlineResponse2004RelatedBooks {
    return InlineResponse2004RelatedBooksFromJSONTyped(json, false);
}

export function InlineResponse2004RelatedBooksFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2004RelatedBooks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'language': !exists(json, 'language') ? undefined : json['language'],
        'shared': !exists(json, 'shared') ? undefined : json['shared'],
    };
}

export function InlineResponse2004RelatedBooksToJSON(value?: InlineResponse2004RelatedBooks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'language': value.language,
        'shared': value.shared,
    };
}


