/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2004Release
 */
export interface InlineResponse2004Release {
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2004Release
     */
    releasedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004Release
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004Release
     */
    comment?: string;
}

export function InlineResponse2004ReleaseFromJSON(json: any): InlineResponse2004Release {
    return InlineResponse2004ReleaseFromJSONTyped(json, false);
}

export function InlineResponse2004ReleaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2004Release {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'releasedAt': !exists(json, 'releasedAt') ? undefined : (new Date(json['releasedAt'])),
        'version': !exists(json, 'version') ? undefined : json['version'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
    };
}

export function InlineResponse2004ReleaseToJSON(value?: InlineResponse2004Release | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'releasedAt': value.releasedAt === undefined ? undefined : (value.releasedAt.toISOString()),
        'version': value.version,
        'comment': value.comment,
    };
}


