/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse200,
    InlineResponse200FromJSON,
    InlineResponse200FromJSONTyped,
    InlineResponse200ToJSON,
    InlineResponse2001Author,
    InlineResponse2001AuthorFromJSON,
    InlineResponse2001AuthorFromJSONTyped,
    InlineResponse2001AuthorToJSON,
    InlineResponse2007LtiLaunchBody,
    InlineResponse2007LtiLaunchBodyFromJSON,
    InlineResponse2007LtiLaunchBodyFromJSONTyped,
    InlineResponse2007LtiLaunchBodyToJSON,
} from './';

/**
 * セッション情報
 * @export
 * @interface InlineResponse2007
 */
export interface InlineResponse2007 {
    /**
     * 
     * @type {InlineResponse2007LtiLaunchBody}
     * @memberof InlineResponse2007
     */
    ltiLaunchBody?: InlineResponse2007LtiLaunchBody;
    /**
     * 
     * @type {InlineResponse200}
     * @memberof InlineResponse2007
     */
    ltiResourceLink?: InlineResponse200;
    /**
     * 
     * @type {InlineResponse2001Author}
     * @memberof InlineResponse2007
     */
    user?: InlineResponse2001Author;
}

export function InlineResponse2007FromJSON(json: any): InlineResponse2007 {
    return InlineResponse2007FromJSONTyped(json, false);
}

export function InlineResponse2007FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2007 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ltiLaunchBody': !exists(json, 'ltiLaunchBody') ? undefined : InlineResponse2007LtiLaunchBodyFromJSON(json['ltiLaunchBody']),
        'ltiResourceLink': !exists(json, 'ltiResourceLink') ? undefined : InlineResponse200FromJSON(json['ltiResourceLink']),
        'user': !exists(json, 'user') ? undefined : InlineResponse2001AuthorFromJSON(json['user']),
    };
}

export function InlineResponse2007ToJSON(value?: InlineResponse2007 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ltiLaunchBody': InlineResponse2007LtiLaunchBodyToJSON(value.ltiLaunchBody),
        'ltiResourceLink': InlineResponse200ToJSON(value.ltiResourceLink),
        'user': InlineResponse2001AuthorToJSON(value.user),
    };
}


