/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse20010Book,
    InlineResponse20010BookFromJSON,
    InlineResponse20010BookFromJSONTyped,
    InlineResponse20010BookToJSON,
    InlineResponse2005Learner,
    InlineResponse2005LearnerFromJSON,
    InlineResponse2005LearnerFromJSONTyped,
    InlineResponse2005LearnerToJSON,
    InlineResponse2005Topic,
    InlineResponse2005TopicFromJSON,
    InlineResponse2005TopicFromJSONTyped,
    InlineResponse2005TopicToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse20010BookActivities
 */
export interface InlineResponse20010BookActivities {
    /**
     * 
     * @type {InlineResponse2005Learner}
     * @memberof InlineResponse20010BookActivities
     */
    learner: InlineResponse2005Learner;
    /**
     * 
     * @type {InlineResponse2005Topic}
     * @memberof InlineResponse20010BookActivities
     */
    topic: InlineResponse2005Topic;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20010BookActivities
     */
    completed?: boolean;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20010BookActivities
     */
    totalTimeMs?: number;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse20010BookActivities
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse20010BookActivities
     */
    updatedAt?: Date;
    /**
     * 
     * @type {InlineResponse20010Book}
     * @memberof InlineResponse20010BookActivities
     */
    book: InlineResponse20010Book;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20010BookActivities
     */
    status: InlineResponse20010BookActivitiesStatusEnum;
}

export function InlineResponse20010BookActivitiesFromJSON(json: any): InlineResponse20010BookActivities {
    return InlineResponse20010BookActivitiesFromJSONTyped(json, false);
}

export function InlineResponse20010BookActivitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20010BookActivities {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'learner': InlineResponse2005LearnerFromJSON(json['learner']),
        'topic': InlineResponse2005TopicFromJSON(json['topic']),
        'completed': !exists(json, 'completed') ? undefined : json['completed'],
        'totalTimeMs': !exists(json, 'totalTimeMs') ? undefined : json['totalTimeMs'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'book': InlineResponse20010BookFromJSON(json['book']),
        'status': json['status'],
    };
}

export function InlineResponse20010BookActivitiesToJSON(value?: InlineResponse20010BookActivities | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'learner': InlineResponse2005LearnerToJSON(value.learner),
        'topic': InlineResponse2005TopicToJSON(value.topic),
        'completed': value.completed,
        'totalTimeMs': value.totalTimeMs,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'book': InlineResponse20010BookToJSON(value.book),
        'status': value.status,
    };
}

/**
* @export
* @enum {string}
*/
export enum InlineResponse20010BookActivitiesStatusEnum {
    completed = 'completed',
    incompleted = 'incompleted',
    unopened = 'unopened'
}


