/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2003LearnerActivities,
    InlineResponse2003LearnerActivitiesFromJSON,
    InlineResponse2003LearnerActivitiesFromJSONTyped,
    InlineResponse2003LearnerActivitiesToJSON,
    InlineResponse2003TopicLearningActivities,
    InlineResponse2003TopicLearningActivitiesFromJSON,
    InlineResponse2003TopicLearningActivitiesFromJSONTyped,
    InlineResponse2003TopicLearningActivitiesToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2003Activity
 */
export interface InlineResponse2003Activity {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2003Activity
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2003Activity
     */
    name: string;
    /**
     * 
     * @type {Array<InlineResponse2003LearnerActivities>}
     * @memberof InlineResponse2003Activity
     */
    learnerActivities: Array<InlineResponse2003LearnerActivities>;
    /**
     * 
     * @type {Array<InlineResponse2003TopicLearningActivities>}
     * @memberof InlineResponse2003Activity
     */
    topicLearningActivities: Array<InlineResponse2003TopicLearningActivities>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2003Activity
     */
    totalLearnerCount: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2003Activity
     */
    completedCount: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2003Activity
     */
    incompletedCount: number;
}

export function InlineResponse2003ActivityFromJSON(json: any): InlineResponse2003Activity {
    return InlineResponse2003ActivityFromJSONTyped(json, false);
}

export function InlineResponse2003ActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2003Activity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'learnerActivities': ((json['learnerActivities'] as Array<any>).map(InlineResponse2003LearnerActivitiesFromJSON)),
        'topicLearningActivities': ((json['topicLearningActivities'] as Array<any>).map(InlineResponse2003TopicLearningActivitiesFromJSON)),
        'totalLearnerCount': json['totalLearnerCount'],
        'completedCount': json['completedCount'],
        'incompletedCount': json['incompletedCount'],
    };
}

export function InlineResponse2003ActivityToJSON(value?: InlineResponse2003Activity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'learnerActivities': ((value.learnerActivities as Array<any>).map(InlineResponse2003LearnerActivitiesToJSON)),
        'topicLearningActivities': ((value.topicLearningActivities as Array<any>).map(InlineResponse2003TopicLearningActivitiesToJSON)),
        'totalLearnerCount': value.totalLearnerCount,
        'completedCount': value.completedCount,
        'incompletedCount': value.incompletedCount,
    };
}


