/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse20013Book
 */
export interface InlineResponse20013Book {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20013Book
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20013Book
     */
    name: string;
}

export function InlineResponse20013BookFromJSON(json: any): InlineResponse20013Book {
    return InlineResponse20013BookFromJSONTyped(json, false);
}

export function InlineResponse20013BookFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20013Book {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function InlineResponse20013BookToJSON(value?: InlineResponse20013Book | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}


