/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2004
 */
export interface InlineResponse2004 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004
     */
    consumerId: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2004
     */
    creatorId: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004
     */
    contextId: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004
     */
    contextTitle: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004
     */
    contextLabel: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2004
     */
    bookId: number;
}

export function InlineResponse2004FromJSON(json: any): InlineResponse2004 {
    return InlineResponse2004FromJSONTyped(json, false);
}

export function InlineResponse2004FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2004 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'consumerId': json['consumerId'],
        'id': json['id'],
        'creatorId': json['creatorId'],
        'contextId': json['contextId'],
        'contextTitle': json['contextTitle'],
        'contextLabel': json['contextLabel'],
        'title': json['title'],
        'bookId': json['bookId'],
    };
}

export function InlineResponse2004ToJSON(value?: InlineResponse2004 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'consumerId': value.consumerId,
        'id': value.id,
        'creatorId': value.creatorId,
        'contextId': value.contextId,
        'contextTitle': value.contextTitle,
        'contextLabel': value.contextLabel,
        'title': value.title,
        'bookId': value.bookId,
    };
}


