/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2001BookSettings,
    InlineResponse2001BookSettingsFromJSON,
    InlineResponse2001BookSettingsFromJSONTyped,
    InlineResponse2001BookSettingsToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2001BookAuthors
 */
export interface InlineResponse2001BookAuthors {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001BookAuthors
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001BookAuthors
     */
    ltiConsumerId: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001BookAuthors
     */
    ltiUserId: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001BookAuthors
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001BookAuthors
     */
    email?: string;
    /**
     * 
     * @type {InlineResponse2001BookSettings}
     * @memberof InlineResponse2001BookAuthors
     */
    settings?: InlineResponse2001BookSettings;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001BookAuthors
     */
    roleName: string;
}

export function InlineResponse2001BookAuthorsFromJSON(json: any): InlineResponse2001BookAuthors {
    return InlineResponse2001BookAuthorsFromJSONTyped(json, false);
}

export function InlineResponse2001BookAuthorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2001BookAuthors {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ltiConsumerId': json['ltiConsumerId'],
        'ltiUserId': json['ltiUserId'],
        'name': json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'settings': !exists(json, 'settings') ? undefined : InlineResponse2001BookSettingsFromJSON(json['settings']),
        'roleName': json['roleName'],
    };
}

export function InlineResponse2001BookAuthorsToJSON(value?: InlineResponse2001BookAuthors | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'ltiConsumerId': value.ltiConsumerId,
        'ltiUserId': value.ltiUserId,
        'name': value.name,
        'email': value.email,
        'settings': InlineResponse2001BookSettingsToJSON(value.settings),
        'roleName': value.roleName,
    };
}


