/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2001Authors,
    InlineResponse2001AuthorsFromJSON,
    InlineResponse2001AuthorsFromJSONTyped,
    InlineResponse2001AuthorsToJSON,
    InlineResponse2001Creator,
    InlineResponse2001CreatorFromJSON,
    InlineResponse2001CreatorFromJSONTyped,
    InlineResponse2001CreatorToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2001Topics
 */
export interface InlineResponse2001Topics {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001Topics
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Topics
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Topics
     */
    language?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001Topics
     */
    timeRequired?: number;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2001Topics
     */
    shared?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Topics
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2001Topics
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2001Topics
     */
    updatedAt?: Date;
    /**
     * 
     * @type {object}
     * @memberof InlineResponse2001Topics
     */
    details?: object;
    /**
     * 
     * @type {Array<InlineResponse2001Authors>}
     * @memberof InlineResponse2001Topics
     */
    authors?: Array<InlineResponse2001Authors>;
    /**
     * 
     * @type {InlineResponse2001Creator}
     * @memberof InlineResponse2001Topics
     */
    creator?: InlineResponse2001Creator;
    /**
     * 
     * @type {object}
     * @memberof InlineResponse2001Topics
     */
    resource?: object;
}

export function InlineResponse2001TopicsFromJSON(json: any): InlineResponse2001Topics {
    return InlineResponse2001TopicsFromJSONTyped(json, false);
}

export function InlineResponse2001TopicsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2001Topics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'language': !exists(json, 'language') ? undefined : json['language'],
        'timeRequired': !exists(json, 'timeRequired') ? undefined : json['timeRequired'],
        'shared': !exists(json, 'shared') ? undefined : json['shared'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'details': !exists(json, 'details') ? undefined : json['details'],
        'authors': !exists(json, 'authors') ? undefined : ((json['authors'] as Array<any>).map(InlineResponse2001AuthorsFromJSON)),
        'creator': !exists(json, 'creator') ? undefined : InlineResponse2001CreatorFromJSON(json['creator']),
        'resource': !exists(json, 'resource') ? undefined : json['resource'],
    };
}

export function InlineResponse2001TopicsToJSON(value?: InlineResponse2001Topics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'language': value.language,
        'timeRequired': value.timeRequired,
        'shared': value.shared,
        'description': value.description,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'details': value.details,
        'authors': value.authors === undefined ? undefined : ((value.authors as Array<any>).map(InlineResponse2001AuthorsToJSON)),
        'creator': InlineResponse2001CreatorToJSON(value.creator),
        'resource': value.resource,
    };
}


