/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2003Learners,
    InlineResponse2003LearnersFromJSON,
    InlineResponse2003LearnersFromJSONTyped,
    InlineResponse2003LearnersToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2003BookActivities
 */
export interface InlineResponse2003BookActivities {
    /**
     * 
     * @type {InlineResponse2003Learners}
     * @memberof InlineResponse2003BookActivities
     */
    learner: InlineResponse2003Learners;
    /**
     * 
     * @type {InlineResponse2003Learners}
     * @memberof InlineResponse2003BookActivities
     */
    topic: InlineResponse2003Learners;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2003BookActivities
     */
    completed?: boolean;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2003BookActivities
     */
    totalTimeMs?: number;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2003BookActivities
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2003BookActivities
     */
    updatedAt?: Date;
    /**
     * 
     * @type {InlineResponse2003Learners}
     * @memberof InlineResponse2003BookActivities
     */
    book: InlineResponse2003Learners;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2003BookActivities
     */
    status: InlineResponse2003BookActivitiesStatusEnum;
}

export function InlineResponse2003BookActivitiesFromJSON(json: any): InlineResponse2003BookActivities {
    return InlineResponse2003BookActivitiesFromJSONTyped(json, false);
}

export function InlineResponse2003BookActivitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2003BookActivities {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'learner': InlineResponse2003LearnersFromJSON(json['learner']),
        'topic': InlineResponse2003LearnersFromJSON(json['topic']),
        'completed': !exists(json, 'completed') ? undefined : json['completed'],
        'totalTimeMs': !exists(json, 'totalTimeMs') ? undefined : json['totalTimeMs'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'book': InlineResponse2003LearnersFromJSON(json['book']),
        'status': json['status'],
    };
}

export function InlineResponse2003BookActivitiesToJSON(value?: InlineResponse2003BookActivities | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'learner': InlineResponse2003LearnersToJSON(value.learner),
        'topic': InlineResponse2003LearnersToJSON(value.topic),
        'completed': value.completed,
        'totalTimeMs': value.totalTimeMs,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'book': InlineResponse2003LearnersToJSON(value.book),
        'status': value.status,
    };
}

/**
* @export
* @enum {string}
*/
export enum InlineResponse2003BookActivitiesStatusEnum {
    Completed = 'completed',
    Incompleted = 'incompleted',
    Unopened = 'unopened'
}


