/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApiV2BookBookIdKeywords,
    ApiV2BookBookIdKeywordsFromJSON,
    ApiV2BookBookIdKeywordsFromJSONTyped,
    ApiV2BookBookIdKeywordsToJSON,
    ApiV2TopicTopicIdResource,
    ApiV2TopicTopicIdResourceFromJSON,
    ApiV2TopicTopicIdResourceFromJSONTyped,
    ApiV2TopicTopicIdResourceToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineObject11
 */
export interface InlineObject11 {
    /**
     * 
     * @type {string}
     * @memberof InlineObject11
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineObject11
     */
    timeRequired?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineObject11
     */
    startTime?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineObject11
     */
    stopTime?: number;
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject11
     */
    shared?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InlineObject11
     */
    description?: string;
    /**
     * 
     * @type {ApiV2TopicTopicIdResource}
     * @memberof InlineObject11
     */
    resource?: ApiV2TopicTopicIdResource;
    /**
     * 
     * @type {Array<ApiV2BookBookIdKeywords>}
     * @memberof InlineObject11
     */
    keywords?: Array<ApiV2BookBookIdKeywords>;
}

export function InlineObject11FromJSON(json: any): InlineObject11 {
    return InlineObject11FromJSONTyped(json, false);
}

export function InlineObject11FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject11 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'timeRequired': !exists(json, 'timeRequired') ? undefined : json['timeRequired'],
        'startTime': !exists(json, 'startTime') ? undefined : json['startTime'],
        'stopTime': !exists(json, 'stopTime') ? undefined : json['stopTime'],
        'shared': !exists(json, 'shared') ? undefined : json['shared'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'resource': !exists(json, 'resource') ? undefined : ApiV2TopicTopicIdResourceFromJSON(json['resource']),
        'keywords': !exists(json, 'keywords') ? undefined : ((json['keywords'] as Array<any>).map(ApiV2BookBookIdKeywordsFromJSON)),
    };
}

export function InlineObject11ToJSON(value?: InlineObject11 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'timeRequired': value.timeRequired,
        'startTime': value.startTime,
        'stopTime': value.stopTime,
        'shared': value.shared,
        'description': value.description,
        'resource': ApiV2TopicTopicIdResourceToJSON(value.resource),
        'keywords': value.keywords === undefined ? undefined : ((value.keywords as Array<any>).map(ApiV2BookBookIdKeywordsToJSON)),
    };
}


