/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse20015Book
 */
export interface InlineResponse20015Book {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20015Book
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20015Book
     */
    name: string;
}

export function InlineResponse20015BookFromJSON(json: any): InlineResponse20015Book {
    return InlineResponse20015BookFromJSONTyped(json, false);
}

export function InlineResponse20015BookFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20015Book {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function InlineResponse20015BookToJSON(value?: InlineResponse20015Book | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}


