/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse20018
 */
export interface InlineResponse20018 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20018
     */
    text: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20018
     */
    value: number;
}

export function InlineResponse20018FromJSON(json: any): InlineResponse20018 {
    return InlineResponse20018FromJSONTyped(json, false);
}

export function InlineResponse20018FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20018 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'text': json['text'],
        'value': json['value'],
    };
}

export function InlineResponse20018ToJSON(value?: InlineResponse20018 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'text': value.text,
        'value': value.value,
    };
}


