/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2005Resource,
    InlineResponse2005ResourceFromJSON,
    InlineResponse2005ResourceFromJSONTyped,
    InlineResponse2005ResourceToJSON,
} from './';

/**
 * 成功時
 * @export
 * @interface InlineResponse20012
 */
export interface InlineResponse20012 {
    /**
     * 
     * @type {Array<InlineResponse2005Resource>}
     * @memberof InlineResponse20012
     */
    resources?: Array<InlineResponse2005Resource>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20012
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20012
     */
    perPage?: number;
}

export function InlineResponse20012FromJSON(json: any): InlineResponse20012 {
    return InlineResponse20012FromJSONTyped(json, false);
}

export function InlineResponse20012FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20012 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resources': !exists(json, 'resources') ? undefined : ((json['resources'] as Array<any>).map(InlineResponse2005ResourceFromJSON)),
        'page': !exists(json, 'page') ? undefined : json['page'],
        'perPage': !exists(json, 'perPage') ? undefined : json['perPage'],
    };
}

export function InlineResponse20012ToJSON(value?: InlineResponse20012 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resources': value.resources === undefined ? undefined : ((value.resources as Array<any>).map(InlineResponse2005ResourceToJSON)),
        'page': value.page,
        'perPage': value.perPage,
    };
}


