/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse20010Releases,
    InlineResponse20010ReleasesFromJSON,
    InlineResponse20010ReleasesFromJSONTyped,
    InlineResponse20010ReleasesToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse20010
 */
export interface InlineResponse20010 {
    /**
     * 
     * @type {Array<InlineResponse20010Releases>}
     * @memberof InlineResponse20010
     */
    releases?: Array<InlineResponse20010Releases>;
}

export function InlineResponse20010FromJSON(json: any): InlineResponse20010 {
    return InlineResponse20010FromJSONTyped(json, false);
}

export function InlineResponse20010FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20010 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'releases': !exists(json, 'releases') ? undefined : ((json['releases'] as Array<any>).map(InlineResponse20010ReleasesFromJSON)),
    };
}

export function InlineResponse20010ToJSON(value?: InlineResponse20010 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'releases': value.releases === undefined ? undefined : ((value.releases as Array<any>).map(InlineResponse20010ReleasesToJSON)),
    };
}


