/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2003Sections,
    InlineResponse2003SectionsFromJSON,
    InlineResponse2003SectionsFromJSONTyped,
    InlineResponse2003SectionsToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2003CourseBooks
 */
export interface InlineResponse2003CourseBooks {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2003CourseBooks
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2003CourseBooks
     */
    name: string;
    /**
     * 
     * @type {Array<InlineResponse2003Sections>}
     * @memberof InlineResponse2003CourseBooks
     */
    sections: Array<InlineResponse2003Sections>;
}

export function InlineResponse2003CourseBooksFromJSON(json: any): InlineResponse2003CourseBooks {
    return InlineResponse2003CourseBooksFromJSONTyped(json, false);
}

export function InlineResponse2003CourseBooksFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2003CourseBooks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'sections': ((json['sections'] as Array<any>).map(InlineResponse2003SectionsFromJSON)),
    };
}

export function InlineResponse2003CourseBooksToJSON(value?: InlineResponse2003CourseBooks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'sections': ((value.sections as Array<any>).map(InlineResponse2003SectionsToJSON)),
    };
}


