/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse20017Sections,
    InlineResponse20017SectionsFromJSON,
    InlineResponse20017SectionsFromJSONTyped,
    InlineResponse20017SectionsToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse20017CourseBooks
 */
export interface InlineResponse20017CourseBooks {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20017CourseBooks
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20017CourseBooks
     */
    name: string;
    /**
     * 
     * @type {Array<InlineResponse20017Sections>}
     * @memberof InlineResponse20017CourseBooks
     */
    sections: Array<InlineResponse20017Sections>;
}

export function InlineResponse20017CourseBooksFromJSON(json: any): InlineResponse20017CourseBooks {
    return InlineResponse20017CourseBooksFromJSONTyped(json, false);
}

export function InlineResponse20017CourseBooksFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20017CourseBooks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'sections': ((json['sections'] as Array<any>).map(InlineResponse20017SectionsFromJSON)),
    };
}

export function InlineResponse20017CourseBooksToJSON(value?: InlineResponse20017CourseBooks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'sections': ((value.sections as Array<any>).map(InlineResponse20017SectionsToJSON)),
    };
}


