/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2001Topics,
    InlineResponse2001TopicsFromJSON,
    InlineResponse2001TopicsFromJSONTyped,
    InlineResponse2001TopicsToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2001Sections
 */
export interface InlineResponse2001Sections {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001Sections
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Sections
     */
    name?: string;
    /**
     * 
     * @type {Array<InlineResponse2001Topics>}
     * @memberof InlineResponse2001Sections
     */
    topics?: Array<InlineResponse2001Topics>;
}

export function InlineResponse2001SectionsFromJSON(json: any): InlineResponse2001Sections {
    return InlineResponse2001SectionsFromJSONTyped(json, false);
}

export function InlineResponse2001SectionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2001Sections {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'topics': !exists(json, 'topics') ? undefined : ((json['topics'] as Array<any>).map(InlineResponse2001TopicsFromJSON)),
    };
}

export function InlineResponse2001SectionsToJSON(value?: InlineResponse2001Sections | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'topics': value.topics === undefined ? undefined : ((value.topics as Array<any>).map(InlineResponse2001TopicsToJSON)),
    };
}


