/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse20022ActivityTimeRangeCounts,
    InlineResponse20022ActivityTimeRangeCountsFromJSON,
    InlineResponse20022ActivityTimeRangeCountsFromJSONTyped,
    InlineResponse20022ActivityTimeRangeCountsToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse20022
 */
export interface InlineResponse20022 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20022
     */
    activityId?: number;
    /**
     * 
     * @type {Array<InlineResponse20022ActivityTimeRangeCounts>}
     * @memberof InlineResponse20022
     */
    activityTimeRangeCounts: Array<InlineResponse20022ActivityTimeRangeCounts>;
}

export function InlineResponse20022FromJSON(json: any): InlineResponse20022 {
    return InlineResponse20022FromJSONTyped(json, false);
}

export function InlineResponse20022FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20022 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'activityId': !exists(json, 'activityId') ? undefined : json['activityId'],
        'activityTimeRangeCounts': ((json['activityTimeRangeCounts'] as Array<any>).map(InlineResponse20022ActivityTimeRangeCountsFromJSON)),
    };
}

export function InlineResponse20022ToJSON(value?: InlineResponse20022 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'activityId': value.activityId,
        'activityTimeRangeCounts': ((value.activityTimeRangeCounts as Array<any>).map(InlineResponse20022ActivityTimeRangeCountsToJSON)),
    };
}


