/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse200Topics,
    InlineResponse200TopicsFromJSON,
    InlineResponse200TopicsFromJSONTyped,
    InlineResponse200TopicsToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse200Sections
 */
export interface InlineResponse200Sections {
    /**
     * 
     * @type {Array<InlineResponse200Topics>}
     * @memberof InlineResponse200Sections
     */
    topics?: Array<InlineResponse200Topics>;
}

export function InlineResponse200SectionsFromJSON(json: any): InlineResponse200Sections {
    return InlineResponse200SectionsFromJSONTyped(json, false);
}

export function InlineResponse200SectionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse200Sections {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'topics': !exists(json, 'topics') ? undefined : ((json['topics'] as Array<any>).map(InlineResponse200TopicsFromJSON)),
    };
}

export function InlineResponse200SectionsToJSON(value?: InlineResponse200Sections | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'topics': value.topics === undefined ? undefined : ((value.topics as Array<any>).map(InlineResponse200TopicsToJSON)),
    };
}


