/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse20019ActivityTimeRangeCounts
 */
export interface InlineResponse20019ActivityTimeRangeCounts {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20019ActivityTimeRangeCounts
     */
    activityId?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20019ActivityTimeRangeCounts
     */
    startMs: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20019ActivityTimeRangeCounts
     */
    endMs: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20019ActivityTimeRangeCounts
     */
    count?: number;
}

export function InlineResponse20019ActivityTimeRangeCountsFromJSON(json: any): InlineResponse20019ActivityTimeRangeCounts {
    return InlineResponse20019ActivityTimeRangeCountsFromJSONTyped(json, false);
}

export function InlineResponse20019ActivityTimeRangeCountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20019ActivityTimeRangeCounts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'activityId': !exists(json, 'activityId') ? undefined : json['activityId'],
        'startMs': json['startMs'],
        'endMs': json['endMs'],
        'count': !exists(json, 'count') ? undefined : json['count'],
    };
}

export function InlineResponse20019ActivityTimeRangeCountsToJSON(value?: InlineResponse20019ActivityTimeRangeCounts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'activityId': value.activityId,
        'startMs': value.startMs,
        'endMs': value.endMs,
        'count': value.count,
    };
}


