/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2003Learner,
    InlineResponse2003LearnerFromJSON,
    InlineResponse2003LearnerFromJSONTyped,
    InlineResponse2003LearnerToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2003Activity
 */
export interface InlineResponse2003Activity {
    /**
     * 
     * @type {InlineResponse2003Learner}
     * @memberof InlineResponse2003Activity
     */
    learner: InlineResponse2003Learner;
    /**
     * 
     * @type {InlineResponse2003Learner}
     * @memberof InlineResponse2003Activity
     */
    topic: InlineResponse2003Learner;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2003Activity
     */
    completed: boolean;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2003Activity
     */
    totalTimeMs: number;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2003Activity
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2003Activity
     */
    updatedAt: Date;
}

export function InlineResponse2003ActivityFromJSON(json: any): InlineResponse2003Activity {
    return InlineResponse2003ActivityFromJSONTyped(json, false);
}

export function InlineResponse2003ActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2003Activity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'learner': InlineResponse2003LearnerFromJSON(json['learner']),
        'topic': InlineResponse2003LearnerFromJSON(json['topic']),
        'completed': json['completed'],
        'totalTimeMs': json['totalTimeMs'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function InlineResponse2003ActivityToJSON(value?: InlineResponse2003Activity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'learner': InlineResponse2003LearnerToJSON(value.learner),
        'topic': InlineResponse2003LearnerToJSON(value.topic),
        'completed': value.completed,
        'totalTimeMs': value.totalTimeMs,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
    };
}


