/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2005Topic,
    InlineResponse2005TopicFromJSON,
    InlineResponse2005TopicFromJSONTyped,
    InlineResponse2005TopicToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse20010Sections
 */
export interface InlineResponse20010Sections {
    /**
     * 
     * @type {Array<InlineResponse2005Topic>}
     * @memberof InlineResponse20010Sections
     */
    topics: Array<InlineResponse2005Topic>;
}

export function InlineResponse20010SectionsFromJSON(json: any): InlineResponse20010Sections {
    return InlineResponse20010SectionsFromJSONTyped(json, false);
}

export function InlineResponse20010SectionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20010Sections {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'topics': ((json['topics'] as Array<any>).map(InlineResponse2005TopicFromJSON)),
    };
}

export function InlineResponse20010SectionsToJSON(value?: InlineResponse20010Sections | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'topics': ((value.topics as Array<any>).map(InlineResponse2005TopicToJSON)),
    };
}


