/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2002Book,
    InlineResponse2002BookFromJSON,
    InlineResponse2002BookFromJSONTyped,
    InlineResponse2002BookToJSON,
    LTIContext,
    LTIContextFromJSON,
    LTIContextFromJSONTyped,
    LTIContextToJSON,
    LTIResourceLinkRequest,
    LTIResourceLinkRequestFromJSON,
    LTIResourceLinkRequestFromJSONTyped,
    LTIResourceLinkRequestToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2002Contents
 */
export interface InlineResponse2002Contents {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002Contents
     */
    oauthClientId: string;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2002Contents
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2002Contents
     */
    updatedAt: Date;
    /**
     * 
     * @type {LTIContext}
     * @memberof InlineResponse2002Contents
     */
    ltiContext: LTIContext;
    /**
     * 
     * @type {LTIResourceLinkRequest}
     * @memberof InlineResponse2002Contents
     */
    ltiResourceLink: LTIResourceLinkRequest;
    /**
     * 
     * @type {InlineResponse2002Book}
     * @memberof InlineResponse2002Contents
     */
    book: InlineResponse2002Book;
}

export function InlineResponse2002ContentsFromJSON(json: any): InlineResponse2002Contents {
    return InlineResponse2002ContentsFromJSONTyped(json, false);
}

export function InlineResponse2002ContentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2002Contents {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'oauthClientId': json['oauthClientId'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'ltiContext': LTIContextFromJSON(json['ltiContext']),
        'ltiResourceLink': LTIResourceLinkRequestFromJSON(json['ltiResourceLink']),
        'book': InlineResponse2002BookFromJSON(json['book']),
    };
}

export function InlineResponse2002ContentsToJSON(value?: InlineResponse2002Contents | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'oauthClientId': value.oauthClientId,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
        'ltiContext': LTIContextToJSON(value.ltiContext),
        'ltiResourceLink': LTIResourceLinkRequestToJSON(value.ltiResourceLink),
        'book': InlineResponse2002BookToJSON(value.book),
    };
}


