/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApiV2LtiMembersUser,
    ApiV2LtiMembersUserFromJSON,
    ApiV2LtiMembersUserFromJSONTyped,
    ApiV2LtiMembersUserToJSON,
    LTIContext,
    LTIContextFromJSON,
    LTIContextFromJSONTyped,
    LTIContextToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse201
 */
export interface InlineResponse201 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse201
     */
    consumerId: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse201
     */
    contextId: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse201
     */
    userId: string;
    /**
     * 
     * @type {ApiV2LtiMembersUser}
     * @memberof InlineResponse201
     */
    user?: ApiV2LtiMembersUser;
    /**
     * 
     * @type {LTIContext}
     * @memberof InlineResponse201
     */
    context?: LTIContext;
}

export function InlineResponse201FromJSON(json: any): InlineResponse201 {
    return InlineResponse201FromJSONTyped(json, false);
}

export function InlineResponse201FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse201 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'consumerId': json['consumerId'],
        'contextId': json['contextId'],
        'userId': json['userId'],
        'user': !exists(json, 'user') ? undefined : ApiV2LtiMembersUserFromJSON(json['user']),
        'context': !exists(json, 'context') ? undefined : LTIContextFromJSON(json['context']),
    };
}

export function InlineResponse201ToJSON(value?: InlineResponse201 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'consumerId': value.consumerId,
        'contextId': value.contextId,
        'userId': value.userId,
        'user': ApiV2LtiMembersUserToJSON(value.user),
        'context': LTIContextToJSON(value.context),
    };
}


