/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2005Learner,
    InlineResponse2005LearnerFromJSON,
    InlineResponse2005LearnerFromJSONTyped,
    InlineResponse2005LearnerToJSON,
    InlineResponse2005Topic,
    InlineResponse2005TopicFromJSON,
    InlineResponse2005TopicFromJSONTyped,
    InlineResponse2005TopicToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2005Activity
 */
export interface InlineResponse2005Activity {
    /**
     * 
     * @type {InlineResponse2005Learner}
     * @memberof InlineResponse2005Activity
     */
    learner: InlineResponse2005Learner;
    /**
     * 
     * @type {InlineResponse2005Topic}
     * @memberof InlineResponse2005Activity
     */
    topic: InlineResponse2005Topic;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2005Activity
     */
    completed: boolean;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2005Activity
     */
    totalTimeMs: number;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2005Activity
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2005Activity
     */
    updatedAt: Date;
}

export function InlineResponse2005ActivityFromJSON(json: any): InlineResponse2005Activity {
    return InlineResponse2005ActivityFromJSONTyped(json, false);
}

export function InlineResponse2005ActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2005Activity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'learner': InlineResponse2005LearnerFromJSON(json['learner']),
        'topic': InlineResponse2005TopicFromJSON(json['topic']),
        'completed': json['completed'],
        'totalTimeMs': json['totalTimeMs'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function InlineResponse2005ActivityToJSON(value?: InlineResponse2005Activity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'learner': InlineResponse2005LearnerToJSON(value.learner),
        'topic': InlineResponse2005TopicToJSON(value.topic),
        'completed': value.completed,
        'totalTimeMs': value.totalTimeMs,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
    };
}


