/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse20013Sections,
    InlineResponse20013SectionsFromJSON,
    InlineResponse20013SectionsFromJSONTyped,
    InlineResponse20013SectionsToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse20013CourseBooks
 */
export interface InlineResponse20013CourseBooks {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20013CourseBooks
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20013CourseBooks
     */
    name: string;
    /**
     * 
     * @type {Array<InlineResponse20013Sections>}
     * @memberof InlineResponse20013CourseBooks
     */
    sections: Array<InlineResponse20013Sections>;
}

export function InlineResponse20013CourseBooksFromJSON(json: any): InlineResponse20013CourseBooks {
    return InlineResponse20013CourseBooksFromJSONTyped(json, false);
}

export function InlineResponse20013CourseBooksFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20013CourseBooks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'sections': ((json['sections'] as Array<any>).map(InlineResponse20013SectionsFromJSON)),
    };
}

export function InlineResponse20013CourseBooksToJSON(value?: InlineResponse20013CourseBooks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'sections': ((value.sections as Array<any>).map(InlineResponse20013SectionsToJSON)),
    };
}


