/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2006Contents,
    InlineResponse2006ContentsFromJSON,
    InlineResponse2006ContentsFromJSONTyped,
    InlineResponse2006ContentsToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2006
 */
export interface InlineResponse2006 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2006
     */
    totalCount: number;
    /**
     * 
     * @type {Array<InlineResponse2006Contents>}
     * @memberof InlineResponse2006
     */
    contents: Array<InlineResponse2006Contents>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2006
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2006
     */
    perPage: number;
}

export function InlineResponse2006FromJSON(json: any): InlineResponse2006 {
    return InlineResponse2006FromJSONTyped(json, false);
}

export function InlineResponse2006FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2006 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'],
        'contents': ((json['contents'] as Array<any>).map(InlineResponse2006ContentsFromJSON)),
        'page': json['page'],
        'perPage': json['perPage'],
    };
}

export function InlineResponse2006ToJSON(value?: InlineResponse2006 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalCount': value.totalCount,
        'contents': ((value.contents as Array<any>).map(InlineResponse2006ContentsToJSON)),
        'page': value.page,
        'perPage': value.perPage,
    };
}


