/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse20017BookActivities,
    InlineResponse20017BookActivitiesFromJSON,
    InlineResponse20017BookActivitiesFromJSONTyped,
    InlineResponse20017BookActivitiesToJSON,
    InlineResponse20017CourseBooks,
    InlineResponse20017CourseBooksFromJSON,
    InlineResponse20017CourseBooksFromJSONTyped,
    InlineResponse20017CourseBooksToJSON,
    InlineResponse2009Learner,
    InlineResponse2009LearnerFromJSON,
    InlineResponse2009LearnerFromJSONTyped,
    InlineResponse2009LearnerToJSON,
} from './';

/**
 * 成功時
 * @export
 * @interface InlineResponse20017
 */
export interface InlineResponse20017 {
    /**
     * 
     * @type {Array<InlineResponse2009Learner>}
     * @memberof InlineResponse20017
     */
    learners: Array<InlineResponse2009Learner>;
    /**
     * 
     * @type {Array<InlineResponse20017CourseBooks>}
     * @memberof InlineResponse20017
     */
    courseBooks: Array<InlineResponse20017CourseBooks>;
    /**
     * 
     * @type {Array<InlineResponse20017BookActivities>}
     * @memberof InlineResponse20017
     */
    bookActivities: Array<InlineResponse20017BookActivities>;
}

export function InlineResponse20017FromJSON(json: any): InlineResponse20017 {
    return InlineResponse20017FromJSONTyped(json, false);
}

export function InlineResponse20017FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20017 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'learners': ((json['learners'] as Array<any>).map(InlineResponse2009LearnerFromJSON)),
        'courseBooks': ((json['courseBooks'] as Array<any>).map(InlineResponse20017CourseBooksFromJSON)),
        'bookActivities': ((json['bookActivities'] as Array<any>).map(InlineResponse20017BookActivitiesFromJSON)),
    };
}

export function InlineResponse20017ToJSON(value?: InlineResponse20017 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'learners': ((value.learners as Array<any>).map(InlineResponse2009LearnerToJSON)),
        'courseBooks': ((value.courseBooks as Array<any>).map(InlineResponse20017CourseBooksToJSON)),
        'bookActivities': ((value.bookActivities as Array<any>).map(InlineResponse20017BookActivitiesToJSON)),
    };
}


