/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse20021ActivityTimeRangeCounts,
    InlineResponse20021ActivityTimeRangeCountsFromJSON,
    InlineResponse20021ActivityTimeRangeCountsFromJSONTyped,
    InlineResponse20021ActivityTimeRangeCountsToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse20021
 */
export interface InlineResponse20021 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20021
     */
    activityId?: number;
    /**
     * 
     * @type {Array<InlineResponse20021ActivityTimeRangeCounts>}
     * @memberof InlineResponse20021
     */
    activityTimeRangeCounts: Array<InlineResponse20021ActivityTimeRangeCounts>;
}

export function InlineResponse20021FromJSON(json: any): InlineResponse20021 {
    return InlineResponse20021FromJSONTyped(json, false);
}

export function InlineResponse20021FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20021 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'activityId': !exists(json, 'activityId') ? undefined : json['activityId'],
        'activityTimeRangeCounts': ((json['activityTimeRangeCounts'] as Array<any>).map(InlineResponse20021ActivityTimeRangeCountsFromJSON)),
    };
}

export function InlineResponse20021ToJSON(value?: InlineResponse20021 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'activityId': value.activityId,
        'activityTimeRangeCounts': ((value.activityTimeRangeCounts as Array<any>).map(InlineResponse20021ActivityTimeRangeCountsToJSON)),
    };
}


