/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse20010Sections,
    InlineResponse20010SectionsFromJSON,
    InlineResponse20010SectionsFromJSONTyped,
    InlineResponse20010SectionsToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse20010CourseBooks
 */
export interface InlineResponse20010CourseBooks {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20010CourseBooks
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20010CourseBooks
     */
    name: string;
    /**
     * 
     * @type {Array<InlineResponse20010Sections>}
     * @memberof InlineResponse20010CourseBooks
     */
    sections: Array<InlineResponse20010Sections>;
}

export function InlineResponse20010CourseBooksFromJSON(json: any): InlineResponse20010CourseBooks {
    return InlineResponse20010CourseBooksFromJSONTyped(json, false);
}

export function InlineResponse20010CourseBooksFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20010CourseBooks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'sections': ((json['sections'] as Array<any>).map(InlineResponse20010SectionsFromJSON)),
    };
}

export function InlineResponse20010CourseBooksToJSON(value?: InlineResponse20010CourseBooks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'sections': ((value.sections as Array<any>).map(InlineResponse20010SectionsToJSON)),
    };
}


