/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse20016Tag,
    InlineResponse20016TagFromJSON,
    InlineResponse20016TagFromJSONTyped,
    InlineResponse20016TagToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse20016TopicBookmarks
 */
export interface InlineResponse20016TopicBookmarks {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20016TopicBookmarks
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20016TopicBookmarks
     */
    updatedAt: string;
    /**
     * 
     * @type {InlineResponse20016Tag}
     * @memberof InlineResponse20016TopicBookmarks
     */
    tag: InlineResponse20016Tag;
}

export function InlineResponse20016TopicBookmarksFromJSON(json: any): InlineResponse20016TopicBookmarks {
    return InlineResponse20016TopicBookmarksFromJSONTyped(json, false);
}

export function InlineResponse20016TopicBookmarksFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20016TopicBookmarks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'updatedAt': json['updatedAt'],
        'tag': InlineResponse20016TagFromJSON(json['tag']),
    };
}

export function InlineResponse20016TopicBookmarksToJSON(value?: InlineResponse20016TopicBookmarks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'updatedAt': value.updatedAt,
        'tag': InlineResponse20016TagToJSON(value.tag),
    };
}


