/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2001Topics
 */
export interface InlineResponse2001Topics {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001Topics
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Topics
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001Topics
     */
    timeRequired?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Topics
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2001Topics
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2001Topics
     */
    updatedAt?: Date;
    /**
     * 
     * @type {object}
     * @memberof InlineResponse2001Topics
     */
    details?: object;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001Topics
     */
    creatorId?: number;
    /**
     * 
     * @type {object}
     * @memberof InlineResponse2001Topics
     */
    resource?: object;
}

export function InlineResponse2001TopicsFromJSON(json: any): InlineResponse2001Topics {
    return InlineResponse2001TopicsFromJSONTyped(json, false);
}

export function InlineResponse2001TopicsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2001Topics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'timeRequired': !exists(json, 'timeRequired') ? undefined : json['timeRequired'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'details': !exists(json, 'details') ? undefined : json['details'],
        'creatorId': !exists(json, 'creatorId') ? undefined : json['creatorId'],
        'resource': !exists(json, 'resource') ? undefined : json['resource'],
    };
}

export function InlineResponse2001TopicsToJSON(value?: InlineResponse2001Topics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'timeRequired': value.timeRequired,
        'description': value.description,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'details': value.details,
        'creatorId': value.creatorId,
        'resource': value.resource,
    };
}


