/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2006Resource,
    InlineResponse2006ResourceFromJSON,
    InlineResponse2006ResourceFromJSONTyped,
    InlineResponse2006ResourceToJSON,
} from './';

/**
 * 成功時
 * @export
 * @interface InlineResponse20015
 */
export interface InlineResponse20015 {
    /**
     * 
     * @type {Array<InlineResponse2006Resource>}
     * @memberof InlineResponse20015
     */
    resources?: Array<InlineResponse2006Resource>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20015
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20015
     */
    perPage?: number;
}

export function InlineResponse20015FromJSON(json: any): InlineResponse20015 {
    return InlineResponse20015FromJSONTyped(json, false);
}

export function InlineResponse20015FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20015 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resources': !exists(json, 'resources') ? undefined : ((json['resources'] as Array<any>).map(InlineResponse2006ResourceFromJSON)),
        'page': !exists(json, 'page') ? undefined : json['page'],
        'perPage': !exists(json, 'perPage') ? undefined : json['perPage'],
    };
}

export function InlineResponse20015ToJSON(value?: InlineResponse20015 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resources': value.resources === undefined ? undefined : ((value.resources as Array<any>).map(InlineResponse2006ResourceToJSON)),
        'page': value.page,
        'perPage': value.perPage,
    };
}


