/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2005ResourceTracks,
    InlineResponse2005ResourceTracksFromJSON,
    InlineResponse2005ResourceTracksFromJSONTyped,
    InlineResponse2005ResourceTracksToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2005Resource
 */
export interface InlineResponse2005Resource {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2005Resource
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2005Resource
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2005Resource
     */
    accessToken?: string;
    /**
     * 
     * @type {object}
     * @memberof InlineResponse2005Resource
     */
    details?: object;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2005Resource
     */
    providerUrl?: string;
    /**
     * 
     * @type {Array<InlineResponse2005ResourceTracks>}
     * @memberof InlineResponse2005Resource
     */
    tracks?: Array<InlineResponse2005ResourceTracks>;
}

export function InlineResponse2005ResourceFromJSON(json: any): InlineResponse2005Resource {
    return InlineResponse2005ResourceFromJSONTyped(json, false);
}

export function InlineResponse2005ResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2005Resource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'accessToken': !exists(json, 'accessToken') ? undefined : json['accessToken'],
        'details': !exists(json, 'details') ? undefined : json['details'],
        'providerUrl': !exists(json, 'providerUrl') ? undefined : json['providerUrl'],
        'tracks': !exists(json, 'tracks') ? undefined : ((json['tracks'] as Array<any>).map(InlineResponse2005ResourceTracksFromJSON)),
    };
}

export function InlineResponse2005ResourceToJSON(value?: InlineResponse2005Resource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'url': value.url,
        'accessToken': value.accessToken,
        'details': value.details,
        'providerUrl': value.providerUrl,
        'tracks': value.tracks === undefined ? undefined : ((value.tracks as Array<any>).map(InlineResponse2005ResourceTracksToJSON)),
    };
}


