/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse20017BookmarkTagMenu
 */
export interface InlineResponse20017BookmarkTagMenu {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20017BookmarkTagMenu
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20017BookmarkTagMenu
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20017BookmarkTagMenu
     */
    emoji: string;
}

export function InlineResponse20017BookmarkTagMenuFromJSON(json: any): InlineResponse20017BookmarkTagMenu {
    return InlineResponse20017BookmarkTagMenuFromJSONTyped(json, false);
}

export function InlineResponse20017BookmarkTagMenuFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20017BookmarkTagMenu {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
        'emoji': json['emoji'],
    };
}

export function InlineResponse20017BookmarkTagMenuToJSON(value?: InlineResponse20017BookmarkTagMenu | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'label': value.label,
        'emoji': value.emoji,
    };
}


