/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2005Learner
 */
export interface InlineResponse2005Learner {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2005Learner
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2005Learner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2005Learner
     */
    email: string;
}

export function InlineResponse2005LearnerFromJSON(json: any): InlineResponse2005Learner {
    return InlineResponse2005LearnerFromJSONTyped(json, false);
}

export function InlineResponse2005LearnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2005Learner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'email': json['email'],
    };
}

export function InlineResponse2005LearnerToJSON(value?: InlineResponse2005Learner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'email': value.email,
    };
}


