/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2003Activities,
    InlineResponse2003ActivitiesFromJSON,
    InlineResponse2003ActivitiesFromJSONTyped,
    InlineResponse2003ActivitiesToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2003LearnerActivities
 */
export interface InlineResponse2003LearnerActivities {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2003LearnerActivities
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2003LearnerActivities
     */
    name: string;
    /**
     * 
     * @type {Array<InlineResponse2003Activities>}
     * @memberof InlineResponse2003LearnerActivities
     */
    activities: Array<InlineResponse2003Activities>;
}

export function InlineResponse2003LearnerActivitiesFromJSON(json: any): InlineResponse2003LearnerActivities {
    return InlineResponse2003LearnerActivitiesFromJSONTyped(json, false);
}

export function InlineResponse2003LearnerActivitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2003LearnerActivities {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'activities': ((json['activities'] as Array<any>).map(InlineResponse2003ActivitiesFromJSON)),
    };
}

export function InlineResponse2003LearnerActivitiesToJSON(value?: InlineResponse2003LearnerActivities | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'activities': ((value.activities as Array<any>).map(InlineResponse2003ActivitiesToJSON)),
    };
}


