/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2009Topic,
    InlineResponse2009TopicFromJSON,
    InlineResponse2009TopicFromJSONTyped,
    InlineResponse2009TopicToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse20017Sections
 */
export interface InlineResponse20017Sections {
    /**
     * 
     * @type {Array<InlineResponse2009Topic>}
     * @memberof InlineResponse20017Sections
     */
    topics: Array<InlineResponse2009Topic>;
}

export function InlineResponse20017SectionsFromJSON(json: any): InlineResponse20017Sections {
    return InlineResponse20017SectionsFromJSONTyped(json, false);
}

export function InlineResponse20017SectionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20017Sections {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'topics': ((json['topics'] as Array<any>).map(InlineResponse2009TopicFromJSON)),
    };
}

export function InlineResponse20017SectionsToJSON(value?: InlineResponse20017Sections | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'topics': ((value.topics as Array<any>).map(InlineResponse2009TopicToJSON)),
    };
}


