/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse20017Stats
 */
export interface InlineResponse20017Stats {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20017Stats
     */
    topicId: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20017Stats
     */
    tagLabel: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20017Stats
     */
    totalCount: number;
}

export function InlineResponse20017StatsFromJSON(json: any): InlineResponse20017Stats {
    return InlineResponse20017StatsFromJSONTyped(json, false);
}

export function InlineResponse20017StatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20017Stats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'topicId': json['topicId'],
        'tagLabel': json['tagLabel'],
        'totalCount': json['totalCount'],
    };
}

export function InlineResponse20017StatsToJSON(value?: InlineResponse20017Stats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'topicId': value.topicId,
        'tagLabel': value.tagLabel,
        'totalCount': value.totalCount,
    };
}


