/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
<<<<<<< HEAD
=======
import {
    ApiV2BookBookIdAuthorsAuthors,
    ApiV2BookBookIdAuthorsAuthorsFromJSON,
    ApiV2BookBookIdAuthorsAuthorsFromJSONTyped,
    ApiV2BookBookIdAuthorsAuthorsToJSON,
} from './';

>>>>>>> main
/**
 * 
 * @export
 * @interface InlineObject4
 */
export interface InlineObject4 {
    /**
     * 
     * @type {Array<ApiV2BookBookIdAuthorsAuthors>}
     * @memberof InlineObject4
     */
<<<<<<< HEAD
    json?: string;
=======
    authors: Array<ApiV2BookBookIdAuthorsAuthors>;
>>>>>>> main
    /**
     * 
     * @type {string}
     * @memberof InlineObject4
     */
<<<<<<< HEAD
    file?: string;
=======
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject4
     */
    wowzaBaseUrl: string;
>>>>>>> main
    /**
     * 
     * @type {string}
     * @memberof InlineObject4
     */
<<<<<<< HEAD
    provider: string;
=======
    json?: string;
>>>>>>> main
    /**
     * 
     * @type {string}
     * @memberof InlineObject4
     */
<<<<<<< HEAD
    wowzaBaseUrl: string;
=======
    file?: string;
>>>>>>> main
}

export function InlineObject4FromJSON(json: any): InlineObject4 {
    return InlineObject4FromJSONTyped(json, false);
}

export function InlineObject4FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject4 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
<<<<<<< HEAD
        'json': !exists(json, 'json') ? undefined : json['json'],
        'file': !exists(json, 'file') ? undefined : json['file'],
        'provider': json['provider'],
        'wowzaBaseUrl': json['wowzaBaseUrl'],
=======
        'authors': ((json['authors'] as Array<any>).map(ApiV2BookBookIdAuthorsAuthorsFromJSON)),
        'provider': json['provider'],
        'wowzaBaseUrl': json['wowzaBaseUrl'],
        'json': !exists(json, 'json') ? undefined : json['json'],
        'file': !exists(json, 'file') ? undefined : json['file'],
>>>>>>> main
    };
}

export function InlineObject4ToJSON(value?: InlineObject4 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
<<<<<<< HEAD
        'json': value.json,
        'file': value.file,
        'provider': value.provider,
        'wowzaBaseUrl': value.wowzaBaseUrl,
=======
        'authors': ((value.authors as Array<any>).map(ApiV2BookBookIdAuthorsAuthorsToJSON)),
        'provider': value.provider,
        'wowzaBaseUrl': value.wowzaBaseUrl,
        'json': value.json,
        'file': value.file,
>>>>>>> main
    };
}


