/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse20017Book,
    InlineResponse20017BookFromJSON,
    InlineResponse20017BookFromJSONTyped,
    InlineResponse20017BookToJSON,
    InlineResponse2009Learner,
    InlineResponse2009LearnerFromJSON,
    InlineResponse2009LearnerFromJSONTyped,
    InlineResponse2009LearnerToJSON,
    InlineResponse2009TimeRanges,
    InlineResponse2009TimeRangesFromJSON,
    InlineResponse2009TimeRangesFromJSONTyped,
    InlineResponse2009TimeRangesToJSON,
    InlineResponse2009Topic,
    InlineResponse2009TopicFromJSON,
    InlineResponse2009TopicFromJSONTyped,
    InlineResponse2009TopicToJSON,
    LTIContext,
    LTIContextFromJSON,
    LTIContextFromJSONTyped,
    LTIContextToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse20017BookActivities
 */
export interface InlineResponse20017BookActivities {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20017BookActivities
     */
    id?: number;
    /**
     * 
     * @type {InlineResponse2009Learner}
     * @memberof InlineResponse20017BookActivities
     */
    learner: InlineResponse2009Learner;
    /**
     * 
     * @type {LTIContext}
     * @memberof InlineResponse20017BookActivities
     */
    ltiContext?: LTIContext;
    /**
     * 
     * @type {InlineResponse2009Topic}
     * @memberof InlineResponse20017BookActivities
     */
    topic: InlineResponse2009Topic;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20017BookActivities
     */
    bookId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20017BookActivities
     */
    completed?: boolean;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20017BookActivities
     */
    totalTimeMs?: number;
    /**
     * 
     * @type {Array<InlineResponse2009TimeRanges>}
     * @memberof InlineResponse20017BookActivities
     */
    timeRanges?: Array<InlineResponse2009TimeRanges>;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse20017BookActivities
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse20017BookActivities
     */
    updatedAt?: Date;
    /**
     * 
     * @type {InlineResponse20017Book}
     * @memberof InlineResponse20017BookActivities
     */
    book: InlineResponse20017Book;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20017BookActivities
     */
    status: InlineResponse20017BookActivitiesStatusEnum;
}

export function InlineResponse20017BookActivitiesFromJSON(json: any): InlineResponse20017BookActivities {
    return InlineResponse20017BookActivitiesFromJSONTyped(json, false);
}

export function InlineResponse20017BookActivitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20017BookActivities {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'learner': InlineResponse2009LearnerFromJSON(json['learner']),
        'ltiContext': !exists(json, 'ltiContext') ? undefined : LTIContextFromJSON(json['ltiContext']),
        'topic': InlineResponse2009TopicFromJSON(json['topic']),
        'bookId': !exists(json, 'bookId') ? undefined : json['bookId'],
        'completed': !exists(json, 'completed') ? undefined : json['completed'],
        'totalTimeMs': !exists(json, 'totalTimeMs') ? undefined : json['totalTimeMs'],
        'timeRanges': !exists(json, 'timeRanges') ? undefined : ((json['timeRanges'] as Array<any>).map(InlineResponse2009TimeRangesFromJSON)),
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'book': InlineResponse20017BookFromJSON(json['book']),
        'status': json['status'],
    };
}

export function InlineResponse20017BookActivitiesToJSON(value?: InlineResponse20017BookActivities | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'learner': InlineResponse2009LearnerToJSON(value.learner),
        'ltiContext': LTIContextToJSON(value.ltiContext),
        'topic': InlineResponse2009TopicToJSON(value.topic),
        'bookId': value.bookId,
        'completed': value.completed,
        'totalTimeMs': value.totalTimeMs,
        'timeRanges': value.timeRanges === undefined ? undefined : ((value.timeRanges as Array<any>).map(InlineResponse2009TimeRangesToJSON)),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'book': InlineResponse20017BookToJSON(value.book),
        'status': value.status,
    };
}

/**
* @export
* @enum {string}
*/
export enum InlineResponse20017BookActivitiesStatusEnum {
    completed = 'completed',
    incompleted = 'incompleted',
    unopened = 'unopened'
}


