/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2003Learner,
    InlineResponse2003LearnerFromJSON,
    InlineResponse2003LearnerFromJSONTyped,
    InlineResponse2003LearnerToJSON,
    InlineResponse2007BookActivities,
    InlineResponse2007BookActivitiesFromJSON,
    InlineResponse2007BookActivitiesFromJSONTyped,
    InlineResponse2007BookActivitiesToJSON,
    InlineResponse2007CourseBooks,
    InlineResponse2007CourseBooksFromJSON,
    InlineResponse2007CourseBooksFromJSONTyped,
    InlineResponse2007CourseBooksToJSON,
    InlineResponse2001Resource,
    InlineResponse2001ResourceFromJSON,
    InlineResponse2001ResourceFromJSONTyped,
    InlineResponse2001ResourceToJSON,
} from './';

/**
 * 成功時
 * @export
 * @interface InlineResponse2007
 */
export interface InlineResponse2007 {
    /**
     * 
     * @type {Array<InlineResponse2003Learner>}
     * @memberof InlineResponse2007
     */
    learners: Array<InlineResponse2003Learner>;
    /**
     * 
     * @type {Array<InlineResponse2007CourseBooks>}
     * @memberof InlineResponse2007
     */
    courseBooks: Array<InlineResponse2007CourseBooks>;
    /**
     * 
     * @type {Array<InlineResponse2007BookActivities>}
     * @memberof InlineResponse2007
     */
    bookActivities: Array<InlineResponse2007BookActivities>;
    /**
     * 
     * @type {Array<InlineResponse2001Resource>}
     * @memberof InlineResponse2007
     */
    resources?: Array<InlineResponse2001Resource>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2007
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2007
     */
    perPage?: number;
}

export function InlineResponse2007FromJSON(json: any): InlineResponse2007 {
    return InlineResponse2007FromJSONTyped(json, false);
}

export function InlineResponse2007FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2007 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'learners': ((json['learners'] as Array<any>).map(InlineResponse2003LearnerFromJSON)),
        'courseBooks': ((json['courseBooks'] as Array<any>).map(InlineResponse2007CourseBooksFromJSON)),
        'bookActivities': ((json['bookActivities'] as Array<any>).map(InlineResponse2007BookActivitiesFromJSON)),
        'resources': !exists(json, 'resources') ? undefined : ((json['resources'] as Array<any>).map(InlineResponse2001ResourceFromJSON)),
        'page': !exists(json, 'page') ? undefined : json['page'],
        'perPage': !exists(json, 'perPage') ? undefined : json['perPage'],
    };
}

export function InlineResponse2007ToJSON(value?: InlineResponse2007 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'learners': ((value.learners as Array<any>).map(InlineResponse2003LearnerToJSON)),
        'courseBooks': ((value.courseBooks as Array<any>).map(InlineResponse2007CourseBooksToJSON)),
        'bookActivities': ((value.bookActivities as Array<any>).map(InlineResponse2007BookActivitiesToJSON)),
        'resources': value.resources === undefined ? undefined : ((value.resources as Array<any>).map(InlineResponse2001ResourceToJSON)),
        'page': value.page,
        'perPage': value.perPage,
    };
}


