/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2001Authors
 */
export interface InlineResponse2001Authors {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001Authors
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Authors
     */
    ltiConsumerId: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Authors
     */
    ltiUserId: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Authors
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Authors
     */
    roleName: string;
}

export function InlineResponse2001AuthorsFromJSON(json: any): InlineResponse2001Authors {
    return InlineResponse2001AuthorsFromJSONTyped(json, false);
}

export function InlineResponse2001AuthorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2001Authors {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ltiConsumerId': json['ltiConsumerId'],
        'ltiUserId': json['ltiUserId'],
        'name': json['name'],
        'roleName': json['roleName'],
    };
}

export function InlineResponse2001AuthorsToJSON(value?: InlineResponse2001Authors | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'ltiConsumerId': value.ltiConsumerId,
        'ltiUserId': value.ltiUserId,
        'name': value.name,
        'roleName': value.roleName,
    };
}


