/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse200Sections,
    InlineResponse200SectionsFromJSON,
    InlineResponse200SectionsFromJSONTyped,
    InlineResponse200SectionsToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse200Books
 */
export interface InlineResponse200Books {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200Books
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200Books
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200Books
     */
    _abstract?: string;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse200Books
     */
    publishedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse200Books
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse200Books
     */
    updatedAt?: Date;
    /**
     * 
     * @type {object}
     * @memberof InlineResponse200Books
     */
    details?: object;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200Books
     */
    authorId?: number;
    /**
     * 
     * @type {Array<InlineResponse200Sections>}
     * @memberof InlineResponse200Books
     */
    sections?: Array<InlineResponse200Sections>;
}

export function InlineResponse200BooksFromJSON(json: any): InlineResponse200Books {
    return InlineResponse200BooksFromJSONTyped(json, false);
}

export function InlineResponse200BooksFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse200Books {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        '_abstract': !exists(json, 'abstract') ? undefined : json['abstract'],
        'publishedAt': !exists(json, 'publishedAt') ? undefined : (new Date(json['publishedAt'])),
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'details': !exists(json, 'details') ? undefined : json['details'],
        'authorId': !exists(json, 'authorId') ? undefined : json['authorId'],
        'sections': !exists(json, 'sections') ? undefined : ((json['sections'] as Array<any>).map(InlineResponse200SectionsFromJSON)),
    };
}

export function InlineResponse200BooksToJSON(value?: InlineResponse200Books | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'abstract': value._abstract,
        'publishedAt': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'details': value.details,
        'authorId': value.authorId,
        'sections': value.sections === undefined ? undefined : ((value.sections as Array<any>).map(InlineResponse200SectionsToJSON)),
    };
}


