/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse20016BookActivities,
    InlineResponse20016BookActivitiesFromJSON,
    InlineResponse20016BookActivitiesFromJSONTyped,
    InlineResponse20016BookActivitiesToJSON,
    InlineResponse20016CourseBooks,
    InlineResponse20016CourseBooksFromJSON,
    InlineResponse20016CourseBooksFromJSONTyped,
    InlineResponse20016CourseBooksToJSON,
    InlineResponse2009Learner,
    InlineResponse2009LearnerFromJSON,
    InlineResponse2009LearnerFromJSONTyped,
    InlineResponse2009LearnerToJSON,
} from './';

/**
 * 成功時
 * @export
 * @interface InlineResponse20016
 */
export interface InlineResponse20016 {
    /**
     * 
     * @type {Array<InlineResponse2009Learner>}
     * @memberof InlineResponse20016
     */
    learners: Array<InlineResponse2009Learner>;
    /**
     * 
     * @type {Array<InlineResponse20016CourseBooks>}
     * @memberof InlineResponse20016
     */
    courseBooks: Array<InlineResponse20016CourseBooks>;
    /**
     * 
     * @type {Array<InlineResponse20016BookActivities>}
     * @memberof InlineResponse20016
     */
    bookActivities: Array<InlineResponse20016BookActivities>;
}

export function InlineResponse20016FromJSON(json: any): InlineResponse20016 {
    return InlineResponse20016FromJSONTyped(json, false);
}

export function InlineResponse20016FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20016 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'learners': ((json['learners'] as Array<any>).map(InlineResponse2009LearnerFromJSON)),
        'courseBooks': ((json['courseBooks'] as Array<any>).map(InlineResponse20016CourseBooksFromJSON)),
        'bookActivities': ((json['bookActivities'] as Array<any>).map(InlineResponse20016BookActivitiesFromJSON)),
    };
}

export function InlineResponse20016ToJSON(value?: InlineResponse20016 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'learners': ((value.learners as Array<any>).map(InlineResponse2009LearnerToJSON)),
        'courseBooks': ((value.courseBooks as Array<any>).map(InlineResponse20016CourseBooksToJSON)),
        'bookActivities': ((value.bookActivities as Array<any>).map(InlineResponse20016BookActivitiesToJSON)),
    };
}


