/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2003Keywords
 */
export interface InlineResponse2003Keywords {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2003Keywords
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2003Keywords
     */
    name: string;
}

export function InlineResponse2003KeywordsFromJSON(json: any): InlineResponse2003Keywords {
    return InlineResponse2003KeywordsFromJSONTyped(json, false);
}

export function InlineResponse2003KeywordsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2003Keywords {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function InlineResponse2003KeywordsToJSON(value?: InlineResponse2003Keywords | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}


