/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineObject13
 */
export interface InlineObject13 {
    /**
     * 
     * @type {number}
     * @memberof InlineObject13
     */
    tagId?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineObject13
     */
    topicId?: number;
}

export function InlineObject13FromJSON(json: any): InlineObject13 {
    return InlineObject13FromJSONTyped(json, false);
}

export function InlineObject13FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject13 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tagId': !exists(json, 'tagId') ? undefined : json['tagId'],
        'topicId': !exists(json, 'topicId') ? undefined : json['topicId'],
    };
}

export function InlineObject13ToJSON(value?: InlineObject13 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tagId': value.tagId,
        'topicId': value.topicId,
    };
}


