/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2006Release,
    InlineResponse2006ReleaseFromJSON,
    InlineResponse2006ReleaseFromJSONTyped,
    InlineResponse2006ReleaseToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2006RelatedBooks
 */
export interface InlineResponse2006RelatedBooks {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2006RelatedBooks
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2006RelatedBooks
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2006RelatedBooks
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2006RelatedBooks
     */
    language?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2006RelatedBooks
     */
    shared?: boolean;
    /**
     * 
     * @type {InlineResponse2006Release}
     * @memberof InlineResponse2006RelatedBooks
     */
    release?: InlineResponse2006Release;
}

export function InlineResponse2006RelatedBooksFromJSON(json: any): InlineResponse2006RelatedBooks {
    return InlineResponse2006RelatedBooksFromJSONTyped(json, false);
}

export function InlineResponse2006RelatedBooksFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2006RelatedBooks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'language': !exists(json, 'language') ? undefined : json['language'],
        'shared': !exists(json, 'shared') ? undefined : json['shared'],
        'release': !exists(json, 'release') ? undefined : InlineResponse2006ReleaseFromJSON(json['release']),
    };
}

export function InlineResponse2006RelatedBooksToJSON(value?: InlineResponse2006RelatedBooks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'language': value.language,
        'shared': value.shared,
        'release': InlineResponse2006ReleaseToJSON(value.release),
    };
}


