/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2001Contents,
    InlineResponse2001ContentsFromJSON,
    InlineResponse2001ContentsFromJSONTyped,
    InlineResponse2001ContentsToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
    /**
     * 
     * @type {Array<InlineResponse2001Contents>}
     * @memberof InlineResponse2001
     */
    contents: Array<InlineResponse2001Contents>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001
     */
    perPage: number;
}

export function InlineResponse2001FromJSON(json: any): InlineResponse2001 {
    return InlineResponse2001FromJSONTyped(json, false);
}

export function InlineResponse2001FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2001 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contents': ((json['contents'] as Array<any>).map(InlineResponse2001ContentsFromJSON)),
        'page': json['page'],
        'perPage': json['perPage'],
    };
}

export function InlineResponse2001ToJSON(value?: InlineResponse2001 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contents': ((value.contents as Array<any>).map(InlineResponse2001ContentsToJSON)),
        'page': value.page,
        'perPage': value.perPage,
    };
}


