/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2005Books,
    InlineResponse2005BooksFromJSON,
    InlineResponse2005BooksFromJSONTyped,
    InlineResponse2005BooksToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2011
 */
export interface InlineResponse2011 {
    /**
     * 
     * @type {Array<InlineResponse2005Books>}
     * @memberof InlineResponse2011
     */
    books?: Array<InlineResponse2005Books>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineResponse2011
     */
    errors?: Array<string>;
}

export function InlineResponse2011FromJSON(json: any): InlineResponse2011 {
    return InlineResponse2011FromJSONTyped(json, false);
}

export function InlineResponse2011FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2011 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'books': !exists(json, 'books') ? undefined : ((json['books'] as Array<any>).map(InlineResponse2005BooksFromJSON)),
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function InlineResponse2011ToJSON(value?: InlineResponse2011 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'books': value.books === undefined ? undefined : ((value.books as Array<any>).map(InlineResponse2005BooksToJSON)),
        'errors': value.errors,
    };
}


