/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2001AuthorSettings,
    InlineResponse2001AuthorSettingsFromJSON,
    InlineResponse2001AuthorSettingsFromJSONTyped,
    InlineResponse2001AuthorSettingsToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2001Author
 */
export interface InlineResponse2001Author {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001Author
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Author
     */
    ltiConsumerId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Author
     */
    ltiUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Author
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Author
     */
    email?: string;
    /**
     * 
     * @type {InlineResponse2001AuthorSettings}
     * @memberof InlineResponse2001Author
     */
    settings?: InlineResponse2001AuthorSettings;
}

export function InlineResponse2001AuthorFromJSON(json: any): InlineResponse2001Author {
    return InlineResponse2001AuthorFromJSONTyped(json, false);
}

export function InlineResponse2001AuthorFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2001Author {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ltiConsumerId': !exists(json, 'ltiConsumerId') ? undefined : json['ltiConsumerId'],
        'ltiUserId': !exists(json, 'ltiUserId') ? undefined : json['ltiUserId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'settings': !exists(json, 'settings') ? undefined : InlineResponse2001AuthorSettingsFromJSON(json['settings']),
    };
}

export function InlineResponse2001AuthorToJSON(value?: InlineResponse2001Author | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'ltiConsumerId': value.ltiConsumerId,
        'ltiUserId': value.ltiUserId,
        'name': value.name,
        'email': value.email,
        'settings': InlineResponse2001AuthorSettingsToJSON(value.settings),
    };
}


