/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2001Settings
 */
export interface InlineResponse2001Settings {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2001Settings
     */
    zoomImportEnabled?: boolean;
}

export function InlineResponse2001SettingsFromJSON(json: any): InlineResponse2001Settings {
    return InlineResponse2001SettingsFromJSONTyped(json, false);
}

export function InlineResponse2001SettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2001Settings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'zoomImportEnabled': !exists(json, 'zoomImportEnabled') ? undefined : json['zoomImportEnabled'],
    };
}

export function InlineResponse2001SettingsToJSON(value?: InlineResponse2001Settings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'zoomImportEnabled': value.zoomImportEnabled,
    };
}


