/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse20019TopicBookmarks,
    InlineResponse20019TopicBookmarksFromJSON,
    InlineResponse20019TopicBookmarksFromJSONTyped,
    InlineResponse20019TopicBookmarksToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse20019Topic
 */
export interface InlineResponse20019Topic {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20019Topic
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20019Topic
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20019Topic
     */
    timeRequired: number;
    /**
     * 
     * @type {Array<InlineResponse20019TopicBookmarks>}
     * @memberof InlineResponse20019Topic
     */
    bookmarks: Array<InlineResponse20019TopicBookmarks>;
}

export function InlineResponse20019TopicFromJSON(json: any): InlineResponse20019Topic {
    return InlineResponse20019TopicFromJSONTyped(json, false);
}

export function InlineResponse20019TopicFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20019Topic {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'timeRequired': json['timeRequired'],
        'bookmarks': ((json['bookmarks'] as Array<any>).map(InlineResponse20019TopicBookmarksFromJSON)),
    };
}

export function InlineResponse20019TopicToJSON(value?: InlineResponse20019Topic | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'timeRequired': value.timeRequired,
        'bookmarks': ((value.bookmarks as Array<any>).map(InlineResponse20019TopicBookmarksToJSON)),
    };
}


