/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LTINRPS20ContextMembershipsMembers,
    LTINRPS20ContextMembershipsMembersFromJSON,
    LTINRPS20ContextMembershipsMembersFromJSONTyped,
    LTINRPS20ContextMembershipsMembersToJSON,
} from './';

/**
 * 
 * @export
 * @interface LTIV13LtiMemberParams
 */
export interface LTIV13LtiMemberParams {
    /**
     * 
     * @type {Array<LTINRPS20ContextMembershipsMembers>}
     * @memberof LTIV13LtiMemberParams
     */
    members: Array<LTINRPS20ContextMembershipsMembers>;
}

export function LTIV13LtiMemberParamsFromJSON(json: any): LTIV13LtiMemberParams {
    return LTIV13LtiMemberParamsFromJSONTyped(json, false);
}

export function LTIV13LtiMemberParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LTIV13LtiMemberParams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'members': ((json['members'] as Array<any>).map(LTINRPS20ContextMembershipsMembersFromJSON)),
    };
}

export function LTIV13LtiMemberParamsToJSON(value?: LTIV13LtiMemberParams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'members': ((value.members as Array<any>).map(LTINRPS20ContextMembershipsMembersToJSON)),
    };
}


