# NOTE: DON'T USE IT IN PRODUCTION. 本番環境で使用しないで。
services:
  mariadb:
    image: "mariadb:11.2.6-jammy"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: bitnami_moodle
    volumes:
      - mariadb_data_v10:/var/lib/mysql
  moodle:
    image: ghcr.io/npocccties/chibichilo-moodle
    build: moodle
    ports: ["8081:8080"]
    environment:
      MOODLE_USERNAME: user
      MOODLE_PASSWORD: password
      ALLOW_EMPTY_PASSWORD: "yes"
      MOODLE_DATABASE_USER: root
      BITNAMI_DEBUG: "true"
    depends_on: [mariadb]
    volumes:
      - moodle_data_v4:/bitnami/moodle
      - moodledata_data_v4:/bitnami/moodledata
  db:
    image: "postgres:17.2-alpine3.21"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: ["5432:5432"]
    volumes:
      - postgres_data_v17:/var/lib/postgresql/data
  app:
    image: "node:22.13.1-alpine3.21"
    environment:
      FRONTEND_ORIGIN: "http://localhost:3000"
      SESSION_SECRET: super_secret_characters_for_session
      OAUTH_CONSUMER_KEY: test
      OAUTH_CONSUMER_SECRET: test
      DATABASE_URL: postgresql://postgres:password@db/postgres
    user: ${UID:-1000}:${GID:-1000}
    command: "sh -c 'cd /app && yarn && yarn dev'"
    volumes: ["./:/app"]
    ports:
      - "3000:3000"
      - "5555:5555"
      - "8080:8080"
    depends_on: [moodle, db]
volumes:
  mariadb_data_v10:
  moodle_data_v4:
  moodledata_data_v4:
  postgres_data_v17:
