const NEXT_PUBLIC_API_BASE_PATH = process.env.NEXT_PUBLIC_API_BASE_PATH ?? "";
const NEXT_PUBLIC_BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

export { NEXT_PUBLIC_API_BASE_PATH, NEXT_PUBLIC_BASE_PATH };
