import yn from "yn";

function readEnv(key: string): string | undefined {
  if (typeof import.meta !== "undefined" && import.meta.env?.[key] !== undefined) {
    return String(import.meta.env[key]);
  }
  return process.env[key];
}

const NEXT_PUBLIC_API_BASE_PATH = readEnv("NEXT_PUBLIC_API_BASE_PATH") ?? "";
const NEXT_PUBLIC_BASE_PATH = readEnv("NEXT_PUBLIC_BASE_PATH") ?? "";
const NEXT_PUBLIC_ACTIVITY_LTI_CONTEXT_ONLY =
  yn(readEnv("NEXT_PUBLIC_ACTIVITY_LTI_CONTEXT_ONLY")) ?? false;
const NEXT_PUBLIC_ACTIVITY_SEND_INTERVAL = Number(
  readEnv("NEXT_PUBLIC_ACTIVITY_SEND_INTERVAL") ?? 10
);
const NEXT_PUBLIC_VIDEO_MAX_HEIGHT =
  readEnv("NEXT_PUBLIC_VIDEO_MAX_HEIGHT") ?? "60vh";
const NEXT_PUBLIC_NO_EMBED = yn(readEnv("NEXT_PUBLIC_NO_EMBED")) ?? false;

const NEXT_PUBLIC_ACTIVITY_REWATCH_RATE_THRESHOLD = Number(
  readEnv("NEXT_PUBLIC_ACTIVITY_REWATCH_RATE_THRESHOLD") ?? 0.1
);
const NEXT_PUBLIC_REWATCH_GRAPH_COUNT_THRESHOLD = Number(
  readEnv("NEXT_PUBLIC_REWATCH_GRAPH_COUNT_THRESHOLD") ?? 20
);
const NEXT_PUBLIC_REWATCH_GRAPH_PLOT_SIZE = Number(
  readEnv("NEXT_PUBLIC_REWATCH_GRAPH_PLOT_SIZE") ?? 5.0
);
const NEXT_PUBLIC_REWATCH_GRAPH_PLOT_COLOR =
  readEnv("NEXT_PUBLIC_REWATCH_GRAPH_PLOT_COLOR") ?? "#00BFFF";

const NEXT_PUBLIC_REWATCH_GRAPH_PLOT_OPACITY = Number(
  readEnv("NEXT_PUBLIC_REWATCH_GRAPH_PLOT_OPACITY") ?? 0.2
);
const NEXT_PUBLIC_ENABLE_TOPIC_VIEW_RECORD =
  yn(readEnv("NEXT_PUBLIC_ENABLE_TOPIC_VIEW_RECORD")) ?? true;

const NEXT_PUBLIC_ENABLE_TAG_AND_BOOKMARK =
  yn(readEnv("NEXT_PUBLIC_ENABLE_TAG_AND_BOOKMARK")) ?? true;

const NEXT_PUBLIC_NO_DEEP_LINK_UI =
  yn(readEnv("NEXT_PUBLIC_NO_DEEP_LINK_UI")) ?? false;
const NEXT_PUBLIC_ACTIVITY_COUNT_INTERVAL = Number(
  readEnv("NEXT_PUBLIC_ACTIVITY_COUNT_INTERVAL") ?? 1
);

const NEXT_PUBLIC_DOWNLOAD_PAGE_SIZE = Number(
  readEnv("NEXT_PUBLIC_DOWNLOAD_PAGE_SIZE") ?? 0
);

export {
  NEXT_PUBLIC_API_BASE_PATH,
  NEXT_PUBLIC_BASE_PATH,
  NEXT_PUBLIC_ACTIVITY_SEND_INTERVAL,
  NEXT_PUBLIC_ACTIVITY_LTI_CONTEXT_ONLY,
  NEXT_PUBLIC_VIDEO_MAX_HEIGHT,
  NEXT_PUBLIC_NO_EMBED,
  NEXT_PUBLIC_ACTIVITY_REWATCH_RATE_THRESHOLD,
  NEXT_PUBLIC_REWATCH_GRAPH_COUNT_THRESHOLD,
  NEXT_PUBLIC_REWATCH_GRAPH_PLOT_SIZE,
  NEXT_PUBLIC_REWATCH_GRAPH_PLOT_COLOR,
  NEXT_PUBLIC_REWATCH_GRAPH_PLOT_OPACITY,
  NEXT_PUBLIC_ENABLE_TOPIC_VIEW_RECORD,
  NEXT_PUBLIC_ENABLE_TAG_AND_BOOKMARK,
  NEXT_PUBLIC_NO_DEEP_LINK_UI,
  NEXT_PUBLIC_ACTIVITY_COUNT_INTERVAL,
  NEXT_PUBLIC_DOWNLOAD_PAGE_SIZE,
};
